airbnb/lunar

.travis.yml
Forgot to disable this before merging my previous PR.
Need to do more alpha testing before official releases.
=> build: Disable auto-releasing in Travis.

package-lock.json, packages/core/package.json, packages/core/src/utils/getWeekdays.ts
Updates to the latest Luxon types, which are more refined.
This blocked release as the types changed and broke the TS build.
Locally.
=> fix: Update to latest Luxon types.

packages/apollo/package.json, packages/app-shell/package.json, packages/core/package.json, packages/forms/package.json, packages/icons/package.json, packages/layouts/package.json, packages/metrics/package.json, packages/test-utils/package.json
- @airbnb/lunar-apollo@1.0.0-alpha.1
- @airbnb/lunar-app-shell@1.0.0-alpha.1
- @airbnb/lunar@1.0.0-alpha.1
- @airbnb/lunar-forms@1.0.0-alpha.1
- @airbnb/lunar-icons@1.0.0-alpha.1
- @airbnb/lunar-layouts@1.0.0-alpha.1
- @airbnb/lunar-metrics@1.0.0-alpha.1
- @airbnb/lunar-test-utils@0.1.1-alpha.0
Can't push to master so need to push to a branch.
N/A
=> build: Release 1.0.0-alpha.1 [ci skip]

.travis.yml, package.json, scripts/.eslintrc, scripts/generateIcon.js, scripts/publishGitHubPages.js
Publish currently fails auth, so let's attempt to use a GH token. The token has been defined via the Travis UI.
Because it's nice.
=> build: Publish styleguide to GitHub pages

packages/apollo/package.json, packages/app-shell/package.json, packages/core/package.json, packages/forms/package.json, packages/icons/package.json, packages/layouts/package.json, packages/metrics/package.json, packages/test-utils/package.json
- @airbnb/lunar-apollo@1.0.0
- @airbnb/lunar-app-shell@1.0.0
- @airbnb/lunar@1.0.0
- @airbnb/lunar-forms@1.0.0
- @airbnb/lunar-icons@1.0.0
- @airbnb/lunar-layouts@1.0.0
- @airbnb/lunar-metrics@1.0.0
- @airbnb/lunar-test-utils@1.0.0
First release!
=> build: Release v1.0.0 [ci skip]

.travis.yml, scripts/publishGitHubPages.js
Fixing problems with DangerJS.
Currently failing builds for contributors.
=> ci: Fix DangerJS issues.

packages/apollo/package.json, packages/app-shell/package.json, packages/core/package.json, packages/forms/package.json, packages/icons/package.json, packages/layouts/package.json, packages/metrics/package.json, packages/test-utils/package.json
- @airbnb/lunar-apollo@1.0.1
- @airbnb/lunar-app-shell@1.0.1
- @airbnb/lunar@1.1.0
- @airbnb/lunar-forms@1.0.1
- @airbnb/lunar-icons@1.0.1
- @airbnb/lunar-layouts@1.0.1
- @airbnb/lunar-metrics@1.0.1
- @airbnb/lunar-test-utils@1.0.1
Still trying to get auto-release working, so manual for now.
=> build: Release [ci skip]

.travis.yml
Looks like Travis checks out a detached head, so lets check out master again.
Get auto-releases working based on: https://github.com/geut/lerna-travis-demo
On Travis.
=> ci: Checkout master before release.

.travis.yml
Temporarily disable this deployment.
It's failing on master because "status checks" aren't met, which is weird since the PR that triggers the merge does pass. I wonder if squashing is breaking it.
=> ci: Temporarily disable auto-release.

.travis.yml
Re-enables the auto release process as we have a new Airbnb bot that will handle this process. Tokens have been updated on the Travis side.
Because it's *nice*.
Will verify on master...
=> ci: Re-enable automatic releases.

package.json
Sadly, the `--github-release` is currently broken: https://github.com/lerna/lerna/issues/2038
Unlock releases.
=> ci: Remove GitHub releases.

packages/core/src/components/DatePickerInput/Input/index.tsx, packages/core/src/components/Empty.story.tsx, packages/core/src/components/Modal.story.tsx, packages/core/src/components/Rating/index.tsx, packages/core/src/components/Table/Cell.tsx, packages/core/src/components/Text/index.tsx, packages/core/src/components/private/BaseCheckBox.tsx, packages/core/src/components/private/BaseRadioButton.tsx, packages/core/src/index.ts, packages/core/src/themes/global.ts, packages/core/test/components/__snapshots__/Rating.test.tsx.snap, packages/core/test/index.test.ts
- Adds wrapping logic/capabilities for text and tables.
- Adds more global styles that are extremely useful.
- Support locale aware fonts.
Feature parity with our old O2 system.
Checked against the style guide.
=> style: Migrate globals and styles from O2 

.eslintrc.js, package-lock.json, package.json, packages/metrics/README.md, packages/metrics/src/index.ts, packages/metrics/src/utils/hasGoogleAnalytics.ts, packages/metrics/test/index.test.ts, types/global.d.ts
to: @milesj @stefhatcher @hayes @Alphy11 
Google Analytics isn't capturing users accurately. 
https://support.google.com/analytics/answer/3123666
Allows setting the Google Analytics user ID in one shared place across all of Lunar's consumers.
Updated tests.
=> update(Metrics): Set Google Analytics userId if able.

packages/icons/src/general/IconCode.tsx, svgs/general/code.svg
cc: @tyn2
Add the code icon from https://material.io/tools/icons/?search=code&icon=code&style=baseline
Used for Guide Designer UI
verified in storybook
=> new(Icons): Add IconCode

packages/core/src/components/TrackingBoundary/index.tsx, packages/core/test/components/TrackingBoundary.test.tsx
Adding a data attribute on tracking boundary tags.
Often times for testing frameworks you will want to select elements based on some html attribute. Using Cypress or React Testing Library for example, these selectors are essential, especially since we use dynamically created class names.  This makes the process easier by using infra we already have for data collection, we can also use for tests.
Unit test.  No new tags were added, just the new attribute.
no visual changes.
=> update(TrackingBoundary): data attribute on tracking-boundary tags

packages/layouts/README.md, packages/layouts/src/components/LayoutShell/index.tsx, packages/layouts/src/index.ts
As the title states.
Noticed this wasn't exported when consuming. This also matches how `app-shell` works.
N/A
=> new: Export LayoutShell from the index

packages/layouts/src/components/LayoutShell/index.tsx, packages/layouts/src/components/SplitLayout/index.tsx, packages/layouts/src/components/ThreeColumnLayout/index.tsx, packages/layouts/src/components/TwoColumnLayout/index.tsx, packages/layouts/src/index.ts, packages/layouts/test/components/LayoutShell.test.tsx
Forgot to remove these when I removed the other prop types.
They're annoying.
Aye.
=> fix: Remove `elementType` prop type usage.

packages/metrics/package.json, packages/metrics/src/index.ts, packages/metrics/src/types.ts, packages/metrics/src/utils/captureBreadcrumb.ts, packages/metrics/src/utils/captureError.ts, packages/metrics/src/utils/captureFinished.ts, packages/metrics/src/utils/hasGoogleAnalytics.ts, packages/metrics/test/index.test.ts, packages/metrics/test/setup.ts, packages/metrics/test/utils/captureBreadcrumb.test.ts, packages/metrics/test/utils/captureError.test.ts, packages/metrics/test/utils/captureFinished.test.ts, yarn.lock
Raven has been deprecated in favor of Sentry. https://github.com/getsentry/sentry-javascript
Adds new `sentry` setting for full/more control.
Stay up to date.
=> new: Migrate from `raven-js` to `@sentry/browser`

packages/core/src/components/Divider.story.tsx, packages/core/src/components/Divider/index.tsx, packages/core/test/components/Divider.test.tsx
A lot of @kenchendesign's designs involve a short divider, it's a pretty small component and I'm happy to just write it for individual apps, but seems like it could be a good fit for this Component.
https://pages.git.musta.ch/ken-chen/airbnb-prototypes/prototype-kit/
I could alternatively make this a `width` prop that takes in an arbitrary value, but in the interest of being opinionated and consistent I think a single option is more appropriate.].
It's just this line haha.
=> update(Divider): Add short prop

packages/apollo/package.json, packages/apollo/src/hooks/useLazyQuery.ts, packages/apollo/src/hooks/useMutation.ts, packages/apollo/src/hooks/useQuery.ts, packages/apollo/src/hooks/useSubscription.ts, yarn.lock
Re-exports the official React hooks.
Because hooks are the future.
N/A
=> new: Add useQuery, useMutation, and more hooks

packages/core/src/components/StatusLabel/index.tsx, packages/core/src/components/Text.story.tsx, packages/core/src/components/Text/index.tsx, packages/core/src/themes/buildFont.ts
From designers, update to base font sizes, line-heights, and letter-spacing.
- For `<Text micro uppercased />`, a `letter-spacing: 1px` is added
- Using relative line-height values, e.g. `1.25` instead of `30px` when the font-size is `24px` 
(30 / 24 = 1.25)
Align Figma and code.
- stories
- local tests
=> style(Text,StatusLabel): Update base font styles.

packages/core/src/components/DataTable.story.tsx, packages/core/src/components/DatePicker.story.tsx, packages/core/src/components/DateTimeSelect.story.tsx, packages/core/src/components/Toast.story.tsx, packages/forms/src/components/DateTimeSelect.story.tsx, packages/forms/src/components/Form.story.tsx
Fixes some of the common false positives. Mostly date related.
Reduce the number of diffs.
=> build: Fix some common Happo issues.

packages/core/src/components/Table/Cell.tsx
Getting errors locally. Want to make children optional.
No more local errors.
Local
=> fix(Cell): Make children optional.

packages/core/src/components/DatePicker/index.tsx, packages/core/src/components/DatePickerInput.story.tsx, packages/core/src/components/DatePickerInput/Input/index.tsx, packages/core/src/components/DatePickerInput/index.tsx, packages/core/src/components/Dropdown/index.tsx, packages/forms/src/components/DatePickerInput.story.tsx, packages/forms/src/components/Form.story.tsx, packages/forms/src/components/Form/DatePickerInput.tsx, packages/forms/src/composers/connectToForm.tsx, packages/forms/src/types.ts, packages/forms/test/components/Form/CheckBox.test.tsx, packages/forms/test/components/Form/CheckBoxController.test.tsx, packages/forms/test/components/Form/DatePickerInput.test.tsx, packages/forms/test/components/Form/FileInput.test.tsx, packages/forms/test/components/Form/Multicomplete.test.tsx, packages/forms/test/components/Form/Switch.test.tsx
- Fixes the `DatePickerInput` overlay closing when changing months.
- Improves the `defaultValue` of all components by refining types.
- Adds more utility to `Dropdown`.
=> feature: Refine form types and fix date related logic.

packages/core/src/components/Chip.story.tsx
adding a story to Chip
make the active option more discoverable
storybook
=> docs(Chip): Add `active` story example.

.travis.yml
This is now covered by GH actions, which is much more secure.
=> ci: Remove DangerJS from Travis.

packages/core/test/components/Accordion/Item.test.tsx
Add a small test condition in order to bump `@airbnb/lunar` (core) package version (patch increase).
I got stuck in some kind of Travis CI race condition with another pull request and the `2.29.0` version that exists does _not_ have my changes from this PR https://github.com/airbnb/lunar/pull/189
There is additional discussion in slack if needed.
`yarn run jest`
N/A
=> misc(AccordionItem): Add test condition in order to bump release version

.github/workflows/publish.yml, .github/workflows/require.yml, .github/workflows/test.yml, .gitignore, .travis.yml, dangerfile.ts, package.json, packages/sizes.json, scripts/computeBuildSizes.ts, tsconfig.node.json, tsconfig.options.json, yarn.lock
Uses danger to report build sizes.
Will help determine when a change increases or decreases a packages build size.
In this PR.
=> build: Report build sizes in each PR

.travis.yml, dangerfile.ts, packages/sizes.json, scripts/computeBuildSizes.ts
Looks like Lerna fails unless the file is committed: https://travis-ci.com/airbnb/lunar/jobs/254257044
=> build: Commit stats file before release.

.travis.yml
During my CI changes, I forgot to run Happo on masters, so our "base" images to diff against are outdated.
Also combinging Jest and ESLint in hopes to speed up build times.
=> ci: Fix Happo builds. Combine Jest and ESLint.

packages/forms/src/components/FilterMenu/index.tsx
use absolute path instead of relative
broke form builds
=> fix(FilterMenu): Fix broken path.

packages/core/src/components/Link/index.tsx, packages/core/src/components/Link/story.tsx, packages/core/test/components/Link.test.tsx
Adding `micro` prop for `Link` component
Needed for Torch design spec
Locally
=> new(Link): Add `micro` sizing.

.travis.yml
No wonder this wasn't working.
I broke it.
=> ci: Build stats before running checks.

.travis.yml, package.json, scripts/checks/compareBuildSizes.ts
- Only reports stats that changed.
- Uses lerna lifecycles to add stats file. https://github.com/lerna/lerna/pull/2335#issuecomment-556337997
Just some polish.
=> ci: Improve stats handling.

packages/core/src/components/Grid/story.tsx, packages/core/src/components/Modal/styles.ts, packages/core/src/components/Overlay/Portal/styles.ts, packages/core/src/themes/buildTheme.ts, packages/core/src/themes/dark.ts, packages/core/src/themes/light.ts, packages/core/src/types.ts
Addition of dark mode colors to support views in Lunar.
Customer support agents would like dark mode for using tools at nighttime.
y - My code follows the style guide of this project.
y - I have updated or added documentation accordingly.
y - I have read the CONTRIBUTING document.
=> feature: Update dark mode!

packages/core/src/themes/dark.ts
Updated two colors for Dark Mode
n/a
y- My code follows the style guide of this project.
y- I have updated or added documentation accordingly.
y- I have read the CONTRIBUTING document.
=> style: Minor polish to dark mode.

packages/core/src/components/Portal/index.tsx, packages/core/src/components/TextArea/Proofreader/index.tsx
fix misc errors we're seeing in new relic:
- `Cannot read property 'slice' of undefined`
- `Cannot read property 'removeChild' of null`
yarn jest
yarn sg
=> fix(Proofreader, Portal): Fix misc js errors.

packages/core/src/components/Accordion/Item.tsx, packages/core/src/components/Accordion/index.tsx, packages/core/src/components/Accordion/story.tsx, packages/core/src/components/Tabs/Tab.tsx, packages/core/test/components/Accordion.test.tsx, packages/core/test/components/Accordion/Item.test.tsx
Adds more handlers for common scenarios. 
We currently have no way to hook into accordion life cycles.
Unit tests.
N/A
=> new(Accordion): Add `onChange` and `onToggle` props.

packages/composer/src/styles.ts, packages/core/src/components/Breadcrumbs/styles.ts, packages/core/src/components/Text/styles.ts
Turns semibold to bold.
Our bold should be 700 according to the designs, but we were using 600.
=> style: Bold, bold, bolder!

packages/composer/src/components/Composer.tsx, packages/composer/src/components/Input/index.tsx, packages/composer/src/helpers/handlers.ts, packages/composer/test/components/Composer.test.tsx, packages/composer/test/components/Input.test.tsx
Will leave comments in the source.
Noticed a few things that could be change while integrating.
Yup.
=> new: Polish and improvements.

packages/composer/src/components/Input/index.tsx, packages/composer/src/helpers/handlers.ts, packages/composer/src/helpers/hotkeys.ts, packages/core/src/components/Autocomplete/index.tsx, packages/core/test/components/Autocomplete.test.tsx
Events were bubbling up and causing issues.
=> fix: Stop propagation for composer and autocomplete.

packages/icons/src/interface/IconReturn.tsx, svgs/interface/return.svg
Adding return icon
Needed for FMQ in Torch
N/A
=> new(Icons): Add return icon.

configs/eslint.js, packages/core/src/components/Copy/index.tsx, packages/core/src/components/DateTimeRange/index.tsx, packages/core/src/components/ErrorMessage/index.tsx, packages/core/src/components/FormActions/index.tsx, packages/core/src/components/FormField/Prefix.tsx, packages/core/src/components/FormField/Suffix.tsx, packages/core/src/components/Multicomplete/private/Chip.tsx, packages/core/src/components/Price/index.tsx, packages/core/src/components/PriceComparison/index.tsx, packages/core/src/components/PriceGroup/index.tsx, packages/core/src/components/ProgressCard/index.tsx, packages/core/src/components/ScrollSection/index.tsx, packages/core/src/components/TrackingBoundary/index.tsx, packages/core/src/components/Translate/index.tsx, packages/core/src/components/private/BaseAffix.tsx, packages/core/test/components/Card/Content.test.tsx, packages/core/test/components/Copy.test.tsx, packages/core/test/components/DateTime.test.tsx, packages/core/test/components/ErrorBoundary/__snapshots__/Tripped.test.tsx.snap, packages/core/test/components/Multicomplete/Chip.test.tsx, packages/core/test/components/TextArea.test.tsx, packages/core/test/components/TrackingBoundary.test.tsx, packages/core/test/components/__snapshots__/Translate.test.tsx.snap, packages/forms/test/components/FilterMenu.test.tsx, packages/icons/src/Icons.story.tsx, packages/icons/src/withIcon.tsx, packages/layouts/src/components/OneColumnLayout/index.tsx, packages/layouts/src/components/TwoColumnLayout/index.tsx
Converts some class components to functions.
Smaller react trees!
=> update: Migrate some class components to function components.

packages/core/src/components/Link/index.tsx, packages/core/test/components/Link.test.tsx
Allow text props to be passed through.
We need all the props for full control.
=> update(Link): Add `textProps` prop.

packages/core/src/components/Tooltip/index.tsx, packages/core/src/components/Tooltip/story.tsx, packages/core/src/components/Tooltip/styles.ts, packages/core/test/components/__snapshots__/Tooltip.test.tsx.snap
- Remove notch.
- Swap default and inverted states.
- Add a global inverted switch.
Designer request.
=> update(Tooltip): Rework styles.

packages/layouts/src/components/Aside/index.tsx, packages/layouts/src/components/Aside/story.tsx
Clean up how side-effects work, with stories to back them up.
This causes a circular loop as they both affect each other.
=> fix(Aside): Clean up side-effects.

packages/core/src/components/Lightbox/index.tsx, packages/core/src/components/Sheet/styles.ts, packages/core/src/themes/buildTheme.ts, packages/core/src/themes/inputStyleSheet.ts
Updates our shadows to:
Large `0px 8px 28px rgba(0, 0, 0, 0.28)`
Default `0px 6px 20px rgba(0, 0, 0, 0.2)`
Small `0px 4px 16px rgba(0, 0, 0, 0.12)`
Just part of the new design.
=> style: Update shadows to new style.

codemods/v3/canonicalPropsState.ts, codemods/v3/i18nKeyContext.ts, packages/core/src/components/CheckBox/index.tsx, packages/core/src/components/CheckBoxController/index.tsx, packages/core/src/components/FormField/index.tsx, packages/core/src/components/RadioButton/index.tsx, packages/core/src/components/RadioButtonController/index.tsx, packages/core/src/components/Select/index.tsx, packages/core/src/components/Switch/index.tsx, packages/core/src/components/Tabs/Tab.tsx, packages/core/src/components/Tabs/index.tsx, packages/core/src/components/ToggleButtonController/index.tsx, packages/core/src/components/private/BaseCheckBox.tsx, packages/core/src/components/private/BaseRadioButton.tsx, packages/core/src/components/private/BaseSelect.tsx, packages/core/src/components/private/BaseSwitch.tsx
Ran into these while migration a project.
=> fix: Handful of fixes based on v3 migration.

packages/core/src/index.ts, packages/metrics/src/index.ts
Other packages have it, so why not these?
Was an oversight.
=> types: Export from index.

packages/composer/src/components/Composer.tsx, packages/composer/src/components/Preview/index.tsx, packages/composer/src/helpers/platform.ts, packages/core/src/components/DataTable/DataTable.tsx, packages/core/src/components/GradientScroller/index.tsx, packages/core/src/components/Lightbox/index.tsx, packages/core/src/components/Modal/private/Inner.tsx, packages/core/src/components/Portal/index.tsx, packages/core/src/utils/focus/focusFirstFocusableChild.ts, packages/core/src/utils/getLocaleFromClient.ts, packages/forms/src/components/Form/DatePickerInput.tsx, packages/metrics/src/index.ts
- Made sure all window/document calls within React happen in an effect or cDM/cDU.
- Add window/document checks around non-React code.
Lunar currently crashes SSR since we access window/document.
Tested storybook so things aren't broken. Testing true SSR will be difficult.
=> fix: Minor changes to support SSR.

packages/core/src/components/DateTime/index.tsx, packages/core/src/components/DateTimeRange/index.tsx, packages/core/src/components/Price/index.tsx, packages/core/src/components/Price/story.tsx, packages/core/src/components/PriceComparison/story.tsx, packages/core/src/components/PriceGroup/index.tsx, packages/core/src/components/PriceGroup/story.tsx, packages/core/src/utils/createDateTime.ts, packages/core/src/utils/formatPrice.ts, packages/core/test/components/Price.test.tsx, packages/core/test/components/PriceComparison.test.tsx, packages/core/test/components/PriceGroup.test.tsx
if and invalid currency like`"[Hidden]"` is given, render `Empty`.
more bad values. follow up of https://github.com/airbnb/lunar/pull/366
- storybook
- added tests
=> update(Price, PriceComparison, PriceGroup): Handle invalid currency values.

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md
to: @williaster 
Removes Hayes as code owner
=> ci: Update PR template and code owners

packages/core/src/components/ImageViewer/story.tsx
=> misc(ImageViewer): Reorder story components 

package.json, yarn.lock
Update fsevents package due to https://github.com/advisories/GHSA-xv2f-5jw4-v95m
Security update
N/A
N/A
=> fix(deps): Update fsevents package to address security vulnerability
