- packages/core/src/components/Toast/index.tsx
- packages/core/test/components/Toast.test.tsx
Adds a new option to toasts that allows the close action to be propagated across tabs and close toasts in other tabs with the same id. 
This is useful for cases like websocket events that may trigger toasts in multiple tabs where you want to use to see the toast in the first tab they visit, but don't want to make the user close the toast in each tab. 
added tests
> new: Add cross tab closes for toasts

- packages/core/src/components/StatusLabel/README.md
- packages/core/src/components/StatusLabel/index.tsx
cc @elibrumbaugh @jpdanks @conglei
This PR adds an optional `compact` prop to `StatusLabel` (closes #769 in lunar).
We have uses for compact labels in multiple projects, below are the specs 
Functional tests with style guide (didn't add additional snapshot tests since we are moving away from them)
New style guide 
> new(StatusLabel): add `compact` option

- packages/core/src/components/FormActions/README.md
- packages/core/src/components/FormActions/index.tsx
- packages/core/test/components/FormActions.test.tsx
Adds a `danger` prop to toggle between normal `Button` and `DangerButton`. Also updated the secondary buttons to `MutedButton`.
Matches new designs.
Unit tests.
> update(FormActions): Add danger prop

- packages/core/src/components/Grid.story.tsx
- packages/core/src/components/Grid/Col.tsx
- packages/core/src/components/Grid/index.tsx
- packages/core/test/components/Grid.test.tsx
these updates help make single column grid layouts more flexible with horizontal alignments:
- `startAlign` for `justify-content: flex-start`
- `centerAlign` for `justify-content: center`
- `endAlign` for `justify-content: flex-end`
also noticed that the offsets were being calculated as `px` instead of `%`. added a fix for that!
updated storybook to demonstrate the changes.
tried to do a single column, centered by offsets and couldn't achieve it. this'll help!
storybook examples
> new(Grid): Add horizontal alignment props. Fix offset % definition.

- packages/core/src/components/Menu/Item.tsx
- packages/core/src/themes/buildInputStyles.ts
- packages/core/src/themes/buildTheme.ts
- packages/core/test/components/Menu/__snapshots__/Item.test.tsx.snap
- packages/core/test/components/__snapshots__/Button.test.tsx.snap
- packages/core/test/components/__snapshots__/DangerButton.test.tsx.snap
- packages/core/test/components/__snapshots__/MutedButton.test.tsx.snap
- packages/core/test/components/private/__snapshots__/FormInput.test.tsx.snap
to: @milesj @stefhatcher
cc: @elibrumbaugh
This PR updates the `Input` and `Menu.Item` to match design and implementation of `Input` and `Row` `Item` padding (and closes #763 in `solar`). It specifically
- decreases `Input` left/right padding from `16px` to `12px` , to match the design spec
- increases `Menu.Item` left/right padding from `8px` to `12px`, to match the design spec (note the original design issue #763 refers to `Autocomplete` items, which are implemented with `Menu.Item`)
**UPDATE**
This also makes the following updates to `Button`, to match the changes to `Input`:
- `small` ~`12, 6`~ => `10, 6` (left/right, top/bottom)
- `regular` ~`16, 10`~ => `12, 10` (now matches default `Input`)
- `large` `20, 12` (no change) 
Design and implementation ideally match ✨ 
Functionally …
> style(Input, Button, MenuItem): Match padding to design specs

- package-lock.json
- packages/core/package.json
- packages/core/src/components/HierarchyPicker.story.tsx
- packages/core/src/components/HierarchyPicker/Hierarchy/HierarchyItem.tsx
- packages/core/src/components/HierarchyPicker/Hierarchy/HierarchyList.tsx
- packages/core/src/components/HierarchyPicker/Hierarchy/ItemDescription.tsx
- packages/core/src/components/HierarchyPicker/Hierarchy/helpers.ts
- packages/core/src/components/HierarchyPicker/Hierarchy/index.tsx
- packages/core/src/components/HierarchyPicker/Picker/index.tsx
- packages/core/src/components/HierarchyPicker/Search/Highlight.tsx
- packages/core/src/components/HierarchyPicker/Search/SearchResult.tsx
- packages/core/src/components/HierarchyPicker/Search/index.tsx
- packages/core/src/components/HierarchyPicker/defaultFormatter.ts
- packages/core/src/components/HierarchyPicker/index.tsx
- packages/core/src/components/HierarchyPicker/types.ts
- packages/core/test/components/HierarchyPicker/Hierarchy.test.tsx
- packages/core/test/components/HierarchyPicker/HierarchyPicker.test.tsx
- packages/core/test/components/HierarchyPicker/Highlight.test.tsx
- packages/core/test/components/HierarchyPicker/Picker.test.tsx
- packages/core/test/components/HierarchyPicker/Search.test.tsx
- packages/core/test/components/HierarchyPicker/SearchResult.test.tsx
- packages/core/test/components/HierarchyPicker/mockItems.ts
to: @milesj @stefhatcher
cc: @elibrumbaugh @jpdanks 
Implements @jpdanks 's 2.0 version of the picker.
**Note** Replaces #43 which got borked 🤦‍♂ 
This PR adds a `HierarchyPicker` `"2.0"` to `@airbnb/lunar`, and is derived mostly from the old `HierarchyPicker` `"1.0"` component (which was removed in the open-source move).
For easier code review, the component architecture / logic basically looks like the following (this is mostly the same vs 1.0):
```jsx
<>
<FauxSelect>
<Portal>
<Autocomplete />
<Hierarchy />
</Portal>
</>
```
The follow changes were made vs the `"1.0"` component:
- adds `verticallyAlign` prop which will result in vertical alignment (vs vertical offset) of nested hierarchy lists. DOM-wise, this results in **_sibling_** `ul`s rather than _**nested**_ `ul`s and required …
> new(HierarchyPicker): Add new picker component

- packages/core/src/utils/removeFocusOnMouseUp.ts
Noticed the outline isn't always removed. Did some debugging and sometimes the remove would be applied to the target, e.g. a child of the the that has focus, and not the actual element that the onClick fired from. so a `blur` on the child wouldn't remove the focus. `currentTarget` solves this. defaults back to `target` for good measure
Wanting that outline to be removed!!
tested locally in the storybook
> fix(removeFocusOnMouseUp): Remove focus from currentTarget.

- packages/core/src/components/Text.story.tsx
- packages/core/src/components/Text/index.tsx
- packages/core/test/components/Text.test.tsx
to: @milesj @stefhatcher
This PR 
- adds a new `startAlign` prop to the `@airbnb/lunar` `Text` component, which is mutually exclusive with the existing `endAlign` and `centerAlign` props
- updates the `storybook` example
Currently `Text` has `centerAlign` and `endAlign` props, which work to control alignment in most cases. 
However, if a parent sets a non-`left` alignment, there is no way to force `startAlign` because `textAlign` [is not set to `left` anywhere in `Text` styles](https://github.com/airbnb/lunar/blob/%40airbnb/lunar%401.4.0/packages/core/src/components/Text/index.tsx#L137) (just `center` and `right` for the current props) and also [is not set by `buildFont`](https://github.com/airbnb/lunar/blob/%40airbnb/lunar%401.4.0/packages/core/src/themes/buildFont.ts#L3).
**Before** …
> update(Text): Add startAlign prop

- packages/core/src/components/Sheet.story.tsx
- packages/core/src/components/Sheet/index.tsx
- packages/core/test/components/Sheet.test.tsx
Adds a section for sheets to pass in their own header content, could be a title, tool bar, or whatever.
We need a tool bar on sheets
> update(Sheet): Add header bar

- packages/core/src/components/DataTable.story.tsx
- packages/core/src/components/DataTable/TableHeader.tsx
- packages/core/src/components/DataTable/index.tsx
- packages/core/src/components/DataTable/types.ts
- packages/core/src/components/private/BaseCheckBox.tsx
- packages/core/test/components/DataTable.test.tsx
to: @milesj @stefhatcher @hayes @alecklandgraf @schillerk
This PR adds a couple usability props to the `DataTable`:
- Adds `showAllRows` prop that will auto-compute and set the `height` of the table to show all rows (including expanded ones)
- Adds `propagateRef` prop that will set a ref to the underlying `react-virtualized` table. I've found this useful for e.g., calling `ref.forceUpdateGrid()` upon data loading with e.g., [`InfiniteLoader`](https://github.com/bvaughn/react-virtualized/blob/master/docs/InfiniteLoader.md)
- Updates the `TableHeader` styles to add a `theme` `background` and use `padding` over `margin` (so `background` takes up the full component background)
Added a storybook example for the `showAllRows` prop.
Features improved usability in another app for me.
**Before** …
> new(DataTable): Add showAllRows and propagateRef props

- packages/core/src/components/Title.story.tsx
- packages/core/src/components/Title/index.tsx
Option to apply the primary theme color to a Title.
Noticed the need for this. Sometimes titles are themed.
- Added an example to the Story
- Local testing
> update(Title): Add primary color prop.

- .storybook/webpack.config.js
- babel.config.js
- package-lock.json
- package.json
- packages/apollo/package.json
- packages/app-shell/package.json
- packages/core/package.json
- packages/forms/package.json
- packages/icons/package.json
- packages/layouts/package.json
- packages/metrics/package.json
I initially setup Lunar to build with Babel runtime + CoreJS v3 for smaller file sizes, but this seems to cause many issues downstream, as using CoreJS v2 and CoreJS v3 in parallel can be quite problematic. It's also complicated to configure correctly (as seen by the storybook config).
While removing the runtime setup, I logged the before and after state of the entire "esm" folder for each package (kilobytes in the table below). While the runtime did have smaller file sizes, it wasn't that much savings in the grand scheme of things. 
| | With runtime | Without |
| ---  | --- | --- |
| apollo | 9,462 | 10,500 |
| app-shell | 8,855 | 9,564 |
| core | 545,207 | 572,108 |
| forms | 40,679 | 39,455 |
| icons | 98,953 | 139,280 |
| layouts | 10,673 …
> fix: Remove Babel runtime setup

- packages/core/src/components/Chip.story.tsx
- packages/core/src/components/Chip/index.tsx
to: @milesj @stefhatcher @hayes @alecklandgraf @kenchendesign 
Is there any reason we don't use `defaultProps` for `Chip`?
Right now, I just use the existing hover state, but Ken's original design uses border color instead of background. I don't know how to make something like this configurable through props since `withStyles` doesn't have access to props and inline styles can't describe hover effects.
See previous discussion here:
https://git.musta.ch/airbnb/solar/issues/824
Tested in storybook.
> update(Chip): Add new compact and active props

- packages/apollo/src/components/Mutation/index.tsx
- packages/apollo/src/components/Query/index.tsx
- packages/apollo/test/components/Mutation.test.tsx
- packages/apollo/test/components/Query.test.tsx
Add a prop to make `<ErrorMessage />` only show up on network errors.  Any graphql errors will pass through `null` values along with the error object.
There are two types of possible errors: Network errors & graphql errors.  We want to pass through graphql errors so that client can a) decide how to display them and b) show the data for the part of the query that succeeded which is often the majority of it.
[Apollo docs](https://www.apollographql.com/docs/react/features/error-handling#options)
Created forced errors and verified that this passes through gql errors and still fails with disconnected wifi
> update(Query,Mutation): Limit error message to network errors

- packages/core/test/components/__snapshots__/Alert.test.tsx.snap
- packages/icons/src/FakeIcon.tsx
- packages/icons/src/Icons.story.tsx
- packages/icons/src/withIcon.tsx
- packages/icons/test/withIcon.test.tsx
Recently had to flip an icon. We chatted and thought this would be nice to bring into Lunar!
Can flip an icon horizontally and/or vertically. There's a transition for an animation.
locally and with storybook
> update(withIcon): Add new icon props to flip horizontally and/or vertically.

- packages/core/src/components/ResponsiveImage.story.tsx
- packages/core/src/components/ResponsiveImage/index.tsx
Adding the option to have an image keep its aspect ratio while contained in its dimensions.
Recently had to add a responsive image that is centered and contained (but not covering) its dimensions for a Lightbox. Adding in preparation for Lunar Lightbox!
- Added an example to Storybook
- Local testing
> update(ResponsiveImage): Add contain prop

- packages/metrics/src/utils/hasGoogleAnalytics.ts
Saw some errors locally using `Metrics.initialize` because `ReferenceError: ga is not defined`. This happened when I changed `global.ga` to `ga`.
Fixes a reference error when `ga` is not present on `window`
Tests still pass.
> fix(Metrics): safely check for ga.

- packages/metrics/src/index.ts
- packages/metrics/test/index.test.ts
Some older Google Analytics docs mention the `USER_ID` should be a `string`, this changes it to that.
Follow best practice to setting Google Analytics `userId`
Updated tests.
> fix(Metrics): set ga userId as string.

- packages/core/src/components/Pagination.story.tsx
- packages/core/src/components/Pagination/index.tsx
- packages/core/test/components/Pagination.test.tsx
Add pageLabel prop so "Page" can be changed to a different text value.
While working on the Lightbox I needed a pagination component without the word "Page". Not all pagination is strictly for pages - we may need to change the label from "Page" to "Photo" or "".
Example:
`pageLabel="Photo"` results in "Photo x" / "Photo x of x"
`pageLabel=""` results in "x" / "x of x"
- Added to Storybook
- Tested locally
> update(Pagination): Add pageLabel prop

- .storybook/components/DataTable/DataTableRenderers/MenuRenderer.jsx
- packages/core/src/components/Chip.story.tsx
- packages/core/src/components/Copy/index.tsx
- packages/core/src/components/DataTable.story.tsx
- packages/core/src/components/DataTable/columns/ExpandableColumn.tsx
- packages/core/src/components/GradientScroller/index.tsx
- packages/core/src/components/HierarchyPicker/Hierarchy/HierarchyItem.tsx
- packages/core/src/components/IconButton.story.tsx
- packages/core/src/components/Menu/Item.tsx
- packages/core/src/components/MessageItem.story.tsx
- packages/core/src/components/Multicomplete/private/Chip.tsx
- packages/core/src/components/SortCarets/index.tsx
- packages/core/src/components/private/BaseCheckBox.tsx
- packages/core/src/components/private/BaseRadioButton.tsx
- packages/core/src/components/private/BaseSwitch.tsx
- packages/core/test/components/Chip.test.tsx
- packages/core/test/components/IconButton.test.tsx
- packages/core/test/components/MenuToggle.test.tsx
- packages/core/test/components/MessageItem.test.tsx
- packages/icons/src/withIcon.tsx
- packages/icons/test/withIcon.test.tsx
- packages/layouts/test/components/SideBar.test.tsx
- packages/layouts/test/components/SideBar/Item.test.tsx
Adding a dev error.
```
'Missing `accessibilityLabel` or `decorative` for accessibility.
```
Seeing Icons in PRs without an a11y prop. This used to throw an error? Needs an error.
Added tests.
> update(withIcon): Throw dev error if an ally prop is missing.

- packages/core/src/components/Pagination.story.tsx
- packages/core/src/components/Pagination/index.tsx
- packages/core/test/components/Pagination.test.tsx
Adds `startAlign`, `centerAlign`, and `endAlign` properties. These props change the placement of the pagination arrows. See screenshots below!
**Note:** Since there's no request for `startAlign` at this time, let me know if I should take it out of this PR.
The Lightbox designs have pagination with arrows aligned around the center of the "Page x of x" text. The designs for table pagination is right aligned with "Page x of x" repositioned to the left of the arrows. This PR adds three options for the arrows - `startAlign`, `centerAlign`, and `endAlign`.
- Added to Storybook
- Tested locally
Design Screenshots:
Storybook Screenshots:
Default:
- …
> new(Pagination): Add arrow startAlign, centerAlign, and endAlign properties

- packages/core/src/components/Pagination.story.tsx
- packages/core/src/components/Pagination/index.tsx
I goofed. When `pageLabel=""` was passed in with `showBookends`, the text would display the number of pages as the page count. (example: 1 of 1, 2 of 2, 3 of 3...) This fixes the issue.
Storybook code:
```
<Pagination
hasPrev
hasNext
showBookends
pageLabel=""
page={2}
pageCount={3}
onNext={action('onNext')}
onPrevious={action('onPrevious')}
/>
```
Before:
After:
> fix(Pagination): Fix page count if label is empty

- packages/core/src/components/Autocomplete.story.tsx
- packages/core/src/components/Autocomplete/index.tsx
- packages/core/src/components/Multicomplete.story.tsx
- packages/core/test/components/Autocomplete.test.tsx
This PR adds a new `loadItemsOnFocus` prop to the `Autocomplete` (and thus `Multicomplete`) component(s). 
The new `loadItemsOnFocus` partially addresses some component limitations described in #26 ([comment](https://github.com/airbnb/lunar/issues/26#issuecomment-496802807)), namely that it is impossible to fetch items upon which we've designed several user experiences around. 
We have tried using the `autoFocus` and `loadItemsOnMount` props, but they do not enable the same functionality and user experience.
Functional (`@airbnb/lunar-core` `Autocomplete`, `Multicomplete`, and `@airbnb/lunar-form` `Autocomplete`) + new unit test.
**Before** (must type to load)
**After** (load on focus)
Multicomplete
- My code follows the style guide of this …
> new(Autocomplete): Add `loadItemsOnFocus` functionality

- codemods/helpers.ts
- codemods/v2/autocompleteProps.ts
- codemods/v2/withStylesCx.ts
- packages/core/src/components/Autocomplete.story.tsx
- packages/core/src/components/Autocomplete/index.tsx
- packages/core/src/components/HierarchyPicker/Search/index.tsx
- packages/core/src/components/Multicomplete.story.tsx
- packages/core/test/components/Autocomplete.test.tsx
- packages/core/test/components/Multicomplete.test.tsx
- packages/forms/src/components/Autocomplete.story.tsx
- packages/forms/src/components/Form.story.tsx
- packages/forms/src/components/Multicomplete.story.tsx
- packages/forms/test/components/Form/Autocomplete.test.tsx
- packages/forms/test/components/Form/Multicomplete.test.tsx
- Renames the `onLoadOptions` to `onLoadItems` (codemod available).
- Also adds a new `disableCache` prop to solve https://github.com/airbnb/lunar/issues/26.
Run the following codemod to migrate the breaking changes.
```
jscodeshift --extensions=js,jsx,ts,tsx --parser=tsx --transform=./path/to/lunar/codemods/v2/autocompleteProps.ts ./src
```
We refer to autocomplete data as "items" not "options", so this was the weird outlier, most likely for legacy reasons with our old UI.
Yes.
> break(Autocomplete,Multicomplete): Rename onLoadOptions to onLoadItems. Add disableCache prop.

- packages/core/src/components/Tabs.story.tsx
- packages/core/src/components/Tabs/Tab.tsx
- packages/core/src/components/private/BaseAffix.tsx
- packages/core/src/components/private/ButtonOrLink.tsx
- packages/core/src/components/private/IconAffix.tsx
- packages/core/src/themes/buildInputStyles.ts
- packages/core/src/themes/buildTheme.ts
- packages/core/src/types.ts
- packages/core/test/components/Tab.test.tsx
- packages/core/test/components/__snapshots__/Tab.test.tsx.snap
- packages/core/test/components/private/ButtonOrLink.test.tsx
Adds an active state that colors text to our primary blurple. This technically isn't a breaking change (except the theme changes below) as the API is the same, but the active state will be broken in consumers based on what label they are passing to `Tab`.
- If you were relying on `Text` for font sizing and color, you should remove them and simply pass a string. Otherwise the active state color will not be used.
```ts
// Before
<Tab key="key" label={<Text>Label</Text>} />
<Tab key="key" label={<Text small>Label</Text>} />
// After
<Tab key="key" label="Label" />
<Tab key="key" label="Label" small />
```
- The theme `borderFocus` accent property has been renamed.
```ts
// Before
theme.color.accent.borderFocus;
// After …
```
> break(Tabs): Rework active state. Add small, beforeIcon, and afterIcon props.

- packages/core/src/components/Card/index.tsx
- packages/core/src/composers/withStyles.tsx
- packages/core/src/composers/withTheme.tsx
- packages/core/src/hooks/useStyles.ts
- packages/core/src/hooks/useTheme.ts
- packages/layouts/src/components/Aside.story.tsx
- packages/layouts/src/components/Aside/index.tsx
- packages/layouts/src/components/Layout.story.tsx
- packages/layouts/src/components/Layout/index.tsx
- packages/layouts/src/components/LayoutShell.story.tsx
- packages/layouts/src/components/LayoutShell/index.tsx
- packages/layouts/src/components/OneColumnLayout.story.tsx
- packages/layouts/src/components/OneColumnLayout/index.tsx
- packages/layouts/src/components/SplitLayout.story.tsx
- packages/layouts/src/components/SplitLayout/index.tsx
- packages/layouts/src/components/ThreeColumnLayout.story.tsx
- packages/layouts/src/components/ThreeColumnLayout/index.tsx
- packages/layouts/src/components/TwoColumnLayout.story.tsx
- packages/layouts/src/components/TwoColumnLayout/index.tsx
- packages/layouts/test/components/Aside.test.tsx
- packages/layouts/test/components/Layout.test.tsx
- packages/layouts/test/components/LayoutShell.test.tsx
- packages/layouts/test/components/OneColumnLayout.test.tsx
- packages/layouts/test/components/SplitLayout.test.tsx
- packages/layouts/test/components/ThreeColumnLayout.test.tsx
- packages/layouts/test/components/TwoColumnLayout.test.tsx
- packages/layouts/test/components/__snapshots__/Layout.test.tsx.snap
- packages/layouts/test/components/__snapshots__/LayoutShell.test.tsx.snap
The current layout architecture is very basic and not at all useful for large applications. It was designed in such a way that the `*Layout` component must always be rendered at the root of the application, since it includes the side/top bars. This is quite problematic once apps become to complex, rely on crazy router logic, and need to adjust their layout based on many factors, but persist the sidebar.
This rework accomplishes the following:
- The side/top bar navigation logic has moved to a new component, `LayoutShell`, which should be rendered near the root. Now these bars will always persist across pages, regardless of how the content/router changes. 
- Asides should now be wrapped in a new `Aside` component, which handles the width, …
> break(Layouts): Rework layout structuring. Add LayoutShell and Aside components.

- packages/core/src/components/DataTable.story.tsx
- packages/core/src/components/DataTable/ColumnLabels.tsx
- packages/core/src/components/DataTable/helpers/sortData.ts
- packages/core/test/components/DataTable.test.tsx
Previously I had flipped sortAsc and sortDesc to do the exact opposite. This didn't ordinarily come up unless developers used the overrideSortDirection prop and wasn't caught until now.
This change corrects sorting order, and adds a test and story for overrideSortDirection.
@milesj I made this change [here](https://github.com/airbnb/lunar/pull/97)) but built it on top of an existing branch and included commits, this is the PR with a clean commit history.
> fix(DataTable): Correct sorting in ascending/descending order

- packages/core/src/components/Chip.story.tsx
- packages/core/src/components/Chip/index.tsx
- packages/core/src/components/Multicomplete/private/Chip.tsx
- packages/core/test/components/Chip.test.tsx
Adds a prop for `before` to `Chip`, allowing developers to pass in an `ReactNode` to render on the left side of the `Chip`.
We could remove `profileImageSrc` since it's now possible to pass in a `ProfilePhoto` directly, but this would be a breaking change. For now, I'm just using `mutuallyExclusiveTrueProps` since passing in both would break formatting.
Could also make sense to rename `icon` to `after`, or even just implement the whole thing as a wrapped `Row`, but again, all breaking changes we'll probably want to avoid for now.
https://git.musta.ch/airbnb/solar/issues/826
Tested in storybook.
> break(Chip): Add beforeIcon and afterIcon props. Remove icon prop.

- packages/core/src/components/StatusLabel.story.tsx
- packages/core/src/components/StatusLabel/index.tsx
- packages/core/test/components/__snapshots__/StatusLabel.test.tsx.snap
before (different heights for default vs bordered):
after:
consistency
storybook
> fix(StatusLabel): Add transparent border for height consistency.

- .storybook/addons/props/Panel.js
- README.md
A few stories are failing with "TypeError: Cannot read property 'length' of undefined". Looks like `Tabs` has an `items` property that doesn't check for existence, so this adds an empty array.
Fix storybook.
> build: Fix Storybook undefined length error

- packages/core/src/components/ToggleButtonController.story.tsx
- packages/core/src/components/ToggleButtonController/index.tsx
- packages/core/test/components/ToggleButtonController.test.tsx
- adds a story showing `<ToggleButtonController compact>` 
- adds a story showing `<ToggleButtonController inline>`
- fixes `compact` to render buttons as `small`: `compact` is not a valid prop for the base button; maps `compact` to `small`
danks and i were chatting! he asked for a story showing compact
locally and test updates
> fix(ToggleButtonController): Fix compact to render small buttons.

- .storybook/addons.js
- .storybook/addons/props/index.js
- .storybook/addons/story/Panel.js
- .storybook/addons/story/index.js
- .storybook/addons/story/register.js
- .storybook/config.js
- .storybook/helpers/stripHOCs.js
- package-lock.json
- package.json
This has been a highly requested feature, so now we display the JSX examples for the stories! It works well for the most part but does not support the following:
- Components that use function children or React context.
- Stories that reference "demo" components.
Make consumption easier.
Storybook, obviously.
> build: Add story examples to Storybook

- packages/core/src/components/Modal.story.tsx
- packages/core/src/components/Modal/index.tsx
- packages/core/src/components/Modal/private/ImageLayout.tsx
- packages/core/src/components/Modal/private/Inner.tsx
- packages/core/src/components/Modal/private/InnerContent.tsx
- packages/core/src/themes/size.ts
- packages/core/src/types.ts
- packages/core/test/components/Modal.test.tsx
Per design specs and prototypes, here are some modal updates:
- close button moved to the right
- padding overhaul
- three widths (more than just default and large):
- base 400px
- medium 600px
- large 800px
- new `fluid` prop to have a % based max width
- new `scrollable` prop to have modal body content have a fixed height with scrollable content
- new `subtitle` prop
- various responsive tweaks
design request (see solar issue)
dark mode example
> update(Modal): Update padding, widths, scrollable content, and layout.

- packages/core/src/components/Accordion.story.tsx
- packages/core/src/components/Accordion/Item.tsx
- packages/core/test/components/Accordion/Item.test.tsx
AccordionItem expects a `title` of string, but this just changes the prop type to more broadly accept a ReactNode.
I had a use case in which I wanted to use AccordionItem, but specifically needed to have a more complex title.
```npm run jest```
and visual check of Storybook story.
Storybook now, with a story and updated `title` prop in the table (showing ReactNode instead of string)
> update(AccordionItem): Change title to node instead of string

- packages/core/src/components/TextArea/Proofreader/Mark.tsx
setting state in CDU causing proofreader to crash. only handle select when selected state has changed.
fix it
local storybook
> fix(Proofreader): Reduce calls in componentDidUpdate.

- packages/core/src/components/Modal/private/InnerContent.tsx
Ensure the close button is on top of modal content.
Noticed this was necessary in an internal modal image viewer.
- locally with storybook
- chrome dev tools
> update(Modal): Add z-index to close button.

- packages/core/src/components/Tooltip/index.tsx
Fixes a JS error where body content is not fully loaded (null) and `getBoundingClientRect` is called. Not sure how, but seeing this error.
Fixing errors.
Works still in the styleguide.
> fix(Tooltip): Fix cannot read property getBoundingClientRect of null.

- packages/core/src/components/Autocomplete.story.tsx
- packages/core/src/components/Autocomplete/index.tsx
- packages/core/src/components/Button/index.tsx
- packages/core/src/components/Input.story.tsx
- packages/core/src/components/Menu/index.tsx
- packages/core/src/components/private/FormInput.tsx
- packages/core/src/themes/buildInputStyles.ts
- packages/core/src/themes/buildTheme.ts
- packages/core/src/types.ts
Changes:
- Decrease `large` spacing from `20px` to `16px`
- Add `large` option to `Input`
- Increase `small` spacing from `6/10` to `8/12`
- Change `MenuRow` in `Autocomplete` to `MenuItem` for No Results and Error states
- Add Spacing to `Autocomplete` Loading state
- Add top/bottom padding to `Menu`
- Subtract border width from spacing calculations
- **[new as of 7/11]** Increase theme borderRadius to 4
A few controversial points:
- The `Input` size props are now `compact` and `large`, ideally this would be `small` and large. I could add the `small` prop with redundant functionality and add a developers note that `compact` will be deprecated and/or we could make this a breaking change in the future.
- First/Last Menu Items now have …
> style(Button,Input,Autocomplete,Menu): Normalize and standardize spacing

- packages/forms/src/composers/connectToForm.tsx
Tried the recent form type changes I made, and it seems to collide with `defaultValue` from `@types/react`, as seen here:
```
src/views/Form.tsx:21:13 - error TS2322: Type 'string | null | undefined' is not assignable to type 'string | string[] | (string & string[]) | (string[] & string) | (string[] & false) | (string[] & true) | undefined'.
Type 'null' is not assignable to type 'string | string[] | (string & string[]) | (string[] & string) | (string[] & false) | (string[] & true) | undefined'.
21             defaultValue={data.name}
~~~~~~~~~~~~
node_modules/@types/react/index.d.ts:1639:9
1639         defaultValue?: string | string[];
~~~~~~~~~~~~
```
Since we provide our own `defaultValue` (and `onChange`), I updated the types to just omit …
> fix: Override defaultValue and onChange prop types.

- packages/core/src/components/Button/index.tsx
This reduces min-width on each of the button sizes and removes the golden ratio calculation.
Values were previously:
52, 78, 104
Values are now:
48, 64, 72
See discussion between @adamirl and @kenchendesign in #dls-for-internaltools
> style(Button): Adjust minimum widths.

- packages/core/src/components/Modal.story.tsx
- packages/core/src/components/Modal/private/Inner.tsx
- packages/core/src/components/Modal/private/InnerContent.tsx
Increasing the max height for scrollable content at the different modal sizes.
small: 160px
regular: 300px
large: 500px
Needing more content to show
Storybook
> style(Modal): Increase modal body height when scrollable is set.

- packages/core/src/components/Row.story.tsx
- packages/core/src/components/Row/index.tsx
- packages/core/test/components/Row.test.tsx
Adds an inline prop, switching the row from being display flex, to flex-inline. When it's inline, its column spacing is the same as compact (8px).
Need it! Handy for after content to be right up against main content with middle alignment as an option!
- added test
- added story
> update(Row): Add inline prop.

- jest.config.js
- packages/apollo/package.json
- packages/apollo/src/components/Mutation.story.tsx
- packages/apollo/src/components/Mutation/index.tsx
- packages/apollo/src/components/Query.story.tsx
- packages/apollo/src/components/Query/index.tsx
- packages/apollo/src/hooks/useLazyQuery.ts
- packages/apollo/src/hooks/useMutation.ts
- packages/apollo/src/hooks/useQuery.ts
- packages/apollo/src/hooks/useSubscription.ts
- packages/apollo/src/updaters/addToList.ts
- packages/apollo/test/components/Mutation.test.tsx
- packages/apollo/test/components/Query.test.tsx
- yarn.lock
cc: @ostrgard
I setup Apollo hooks the other day here: https://github.com/airbnb/lunar/pull/138
Turns out they don't work as `react-apollo` and `@apollo/react-hooks` have different contexts/providers, so the consumers aren't compatible. This PR updates to the `react-apollo` beta which includes hooks and should resolve our reference issue.
Changelog: https://github.com/apollographql/react-apollo/blob/master/Changelog.md
Hooks don't work otherwise.
Updated the unit tests, but since Enzyme doesn't support hooks very well, they are still quite hard to test.
> update: Upgrade `react-apollo` to latest beta. Support native hooks.

- packages/core/src/components/Text.story.tsx
- packages/core/src/themes/buildFont.ts
After seeing the new line-heights out in the wild, we decided to go back to values closer to the original values (dropping the `.5px` on a few).
Also update the `<Text />` story to show more text so the line-height difference is easier to preview.
`20px` was too dense and affected buttons, inputs, and text heavy areas.
storybook
> style(Text): Update line-height.

- packages/core/src/components/TextArea/Proofreader/index.tsx
`isRuleHighlighted` and `isRuleSecondary` were being spuriously passed to BaseTextArea. This change uses spread syntax to pull them out beforehand. 
My previous change https://github.com/airbnb/lunar/pull/82 introduced new proofreader-specific props that BaseTextArea is unaware of. We were still passing them to BaseTextArea though, which created unknown prop warnings that we're now eliminating. 
Verified locally that there's no longer an unknown prop warning. 
> fix(Proofreader): Pull spurious, proofread-specific props from being passed to TextArea

- packages/core/src/components/Modal.story.tsx
- packages/core/src/components/Modal/private/InnerContent.tsx
- packages/core/test/components/__snapshots__/DateTime.test.tsx.snap
Adds more adding to the right of the modal header to wrap long titles.
Also:
- Added a long title to the stories
- Set modal visibility to true in the stories
- Turned on happo for modal stories
Noticed long titles get covered up by the close button.
Storybook
before:
after:
> fix(Modal): Add padding to right of header to prevent close overlapping with long titles.

- packages/core/src/components/Breadcrumbs/Breadcrumb.tsx
- packages/core/src/components/Chip/index.tsx
- packages/core/src/components/Copy/index.tsx
- packages/core/src/components/Menu/Item.tsx
- packages/core/test/components/Breadcrumbs/Breadcrumb.test.tsx
- packages/core/test/components/Chip.test.tsx
- packages/core/test/components/Copy.test.tsx
- packages/core/test/components/Menu/Item.test.tsx
to: @milesj @stefhatcher @hayes 
Allows passing an `id` prop to `Copy`, which is passed through to `Link`
Links and Buttons with an `id` can be tracked easier. 
Updated tests. 
> update(Copy, MenuItem): Allow id to pass through to Link for tracking

- packages/core/src/components/Link.story.tsx
- packages/core/src/themes/global.ts
Fixes font styles so that they are inherited. For example, `Link` bold tests.
Before:
After (added a new line):
I've noticed here and there that some styles were missing, or being overridden by browser agent styles, mostly font related stuff.
Problematic styles (font weight should be 600):
> style: Override native agent font styles.

- packages/core/src/components/DataTable/ColumnLabels.tsx
- packages/core/src/components/SortCarets.story.tsx
- packages/core/src/components/SortCarets/index.tsx
- packages/core/test/components/SortCarets.test.tsx
cc: @schillerk 
Noticed the `SortCarets` kind of break down in some designs as the sizing isn't restrictive. This updates to be explicit.
Just a little polish.
> update(SortCarets): Clean up styles. Add tests and story.

- packages/core/src/components/ImageViewer/RotateControls.tsx
- packages/core/src/components/ImageViewer/ZoomControls.tsx
Whoops! The links to icons in Rotate and Zoom controls were `src` when they should have been `lib`.
> fix(ImageViewer): Fix icon path from src to lib.

- packages/forms/src/components/Form/index.tsx
Fixes the form context not propagating to consumers. Was caused by my over optimization in a previous PR.
It breaks consumers that rely on form state.
> fix(Form): Fix `FormContext` not propagating.

- packages/core/src/components/Breadcrumbs/Breadcrumb.tsx
- packages/core/src/components/Chip/index.tsx
- packages/core/src/components/Copy/index.tsx
- packages/core/src/components/Menu/Item.tsx
- packages/core/src/components/private/ButtonOrLink.tsx
- packages/core/test/components/Breadcrumbs/Breadcrumb.test.tsx
- packages/core/test/components/Chip.test.tsx
- packages/core/test/components/Copy.test.tsx
- packages/core/test/components/Menu/Item.test.tsx
- packages/core/test/components/private/ButtonOrLink.test.tsx
Adds `trackingName` which will follow our convention of adding a `data-tracking-name` attribute on button and anchor elements. 
`id` should be unique across the page. When `id` is used in reusable components, it can be difficult or impossible for consumers to provide a unique `id`. Adding `data-tracking-name` is a better alternative for tracking. 
https://www.w3.org/TR/html4/struct/global.html#h-7.5.2
Future PRs can add `trackingName` and `data-tracking-name` as needed to provide tracking context for analytics. 
Updated tests. 
> update(Copy, Chip, Breadcrumb, MenuItem): Add data-tracking-name

- packages/core/src/components/DataTable.story.tsx
- packages/core/src/components/DataTable/index.tsx
- packages/core/src/components/DataTable/types.ts
- packages/core/test/components/DataTable.test.tsx
Currently, the only want to interact with selectedRows from outside DataTable is to configure custom header buttons. This satisfied the existing use case for Bighead of selecting rows and then performing an action on them, but there have been requests for having access to selections as a callback.
This PR adds a new prop for users to pass in a function, and then adds it as a `setState` callback when we update `selectedRows`
> update(DataTable): add prop for callback on row selection

- .storybook/components/DataTable/DataTableData.jsx
- packages/core/src/components/DataTable.story.tsx
- packages/core/src/components/DataTable/helpers/sortData.ts
- packages/core/test/components/DataTable.test.tsx
Currently undefined values are treated as small values, and null values don't get any special treatment. Chris Council and @williaster have both asked for this new treatment, with null and undefined sorted last regardless of ascending/descending order.
> update(DataTable): Sort null and undefined last.

- packages/core/src/components/DataTable/TableHeader.tsx
- packages/core/src/components/DataTable/index.tsx
There's a top border on ColumnHeaders to separate them from the header label, but this is unnecessary when the header label is absent and adds extra visual noise.
Feature request from Ken Chen.
> update(DataTable): Only render top border when there's a header.

- packages/core/src/components/DataTable.story.tsx
- packages/core/src/components/DataTable/helpers/expandData.ts
- packages/core/src/components/DataTable/helpers/sortData.ts
- packages/core/src/components/DataTable/index.tsx
- packages/core/src/components/DataTable/types.ts
- packages/core/test/components/DataTable.test.tsx
Independent of sorting, this allows developers to pass in a prop so that selected rows are always displayed first. Does not apply to children, but does sort selected -> hasChildrenSelected -> unselected.
Xuan Lu requested this change, it seems reasonable and could be useful in other applications as well. The user interaction is a little janky because you select a row, and then it immediately jumps to the top.
> update(DataTable): Add `selectedRowsFirst` prop.

- packages/core/src/components/FormField/index.tsx
Stumbled upon this CSS-in-JS typo related to `alignItems`. Not really sure where this is actually used (my guess is that it isn't), but putting in this PR to draw attention to it.
Correctness. Though, arguably, if no one has noticed it by now, maybe it doesn't make a difference and the rule ought to be removed. I think it'd have to be a case where you want both an `inline` and a `topAlign`ed FormField - but i don't see how to actually pass in topAlign to a FormField, since it's not part of FormField's Props or properly assigned in `partitionFieldProps`.
TODO
TODO
> fix(FormField): Fix CSS typo.

- packages/core/src/components/Dropdown/index.tsx
Removes the prop type restrictions. Not sure why these were here since its valid to define them in parallel.
I have a use case where I need to define left and right at the same time, yet it currently errors.
> fix(Dropdown): Remove prop type restrictions.

- packages/core/src/components/EmojiPicker/index.tsx
Noticed the skin tone selection was off.
It was ugly.
Before: (shadow coming from another app, not lunar)
After:
> style(EmojiPicker): Tighten up header spacing

- packages/core/src/components/ImageViewer/index.tsx
Moved the use of flexbox for ImageViewer from outer div to inner div, and set width and height to 100%. There are no visual or functional changes.
This fix is needed for the ImageViewer to be used in the Lightbox.
No visual changes
> style(ImageViewer): Move flexbox from outer to inner div

- packages/core/src/components/MenuToggle.story.tsx
- packages/core/src/components/MenuToggle/index.tsx
- packages/core/test/components/MenuToggle.test.tsx
Add a `disabled` property to `MenuToggle` which disables the entire menu dropdown.
Currently it is only possible to disable each `MenuItem` individually - but if you want to disable the `MenuToggle` dropdown itself, you cannot.
Added new test and tested in storybook.
Disabled (from storybook):
> update(MenuToggle): Add `disabled` support.

- packages/core/src/components/DataTable/columns/renderSelectableColumn.tsx
> fix(DataTable): Add spacing to prevent clipping checkbox focus.

- packages/core/src/components/Accordion.story.tsx
- packages/core/src/components/Accordion/Item.tsx
- packages/core/test/components/Accordion/Item.test.tsx
Add a `noSpacing` property to `AccordionItem` component. This disables the horizontal padding of the accordion item title and the vertical and horizontal padding of the accordion item body.
Introducing this property allows for consumers to customize how padding works in the accordion without using negative margins. However, even if using negative margins, the consumer has no control over the accordion item title's padding, so this is required to achieve certain designs.
Add new test and manually tested in storybook.
From storybook:
> update(AccordionItem): Add `noSpacing` support.

- packages/apollo/src/index.ts
- packages/apollo/test/index.test.ts
~**WIP:** Not sure what's wrong with my test - creating PR to see if it's a local issue~ 
All checks passed ✅ 
to: @milesj @stefhatcher @hayes @alecklandgraf 
Adds a resolvers option to Apollo settings.
If an engineer wants to use Lunar's Apollo package and [Apollo's local state](https://www.apollographql.com/docs/react/essentials/local-state/#local-resolvers), they currently cannot set `resolvers` when Apollo initializes. This fixes that.
- unit tests
> update(Apollo): Add resolvers to Apollo settings

- packages/core/src/components/Accordion/Item.tsx
Literally add the word `the` to a component prop comment. I expect this would create a new release since you can see these comments in the provided typings file.
I need a lunar release. `2.29.0` doesn't contain what it should.
N/A
N/A
> docs(AccordionItem): Comment update.

- packages/core/src/components/Tabs.story.tsx
- packages/core/src/components/Tabs/index.tsx
- packages/core/test/components/Tabs.test.tsx
if `persistWithHash`, listen for `popstate`
When navigating thru tabs, users want the browser Back button to be functional
Please advise
no visual changes
> fix(Tabs): Persist active tab when back button is used.

- .github/workflows/publish.yml
- .travis.yml
- package.json
We're doing double builds on master. Since Happo/Storybook is also built from GitHub actions, let's just use those instead. 
This should speed up the releases process a bit.
> ci: Remove Happo and Storybook from Travis.

- .travis.yml
Brings back Happo for PRs only, not master.
In my previous PR, I removed Happo and Storybook as it was covered by GH actions. However, actions aren't available for forks yet, so happo never runs on those PRs.
https://github.com/airbnb/lunar/pull/171
> ci: Bring back Happo for PRs.

- packages/core/src/components/List.story.tsx
- packages/core/src/components/List/index.tsx
- packages/core/test/components/List.test.tsx
This adds  a `gutter` prop to add margin spacing between child `<li>`s.
After refactoring some code, having some margins between `li` would be nice, without using `List`'s `Item`. 
story book
tests
> update(List): Add `gutter` prop for space between list items.

- packages/core/src/components/Card.story.tsx
- packages/core/src/components/Card/Content.tsx
- packages/core/src/components/Image.story.tsx
- packages/core/src/components/Image/index.tsx
- packages/core/src/components/Row.story.tsx
- packages/core/src/components/Row/index.tsx
- packages/core/test/components/Card/Content.test.tsx
to: @Alphy11 
Remake of https://github.com/airbnb/lunar/pull/195/ since Happo is broken.
> - Changing default size for Content before/after images to be 152px
> - Adding small size for Content before/after images at previous default of 80px
> - Changing the Image to use background so that the card scales with the content of the card, not the image.
> - Add a minHeight to Content
> - Add a minHeight to Row
> The focus of a card is its' content, and we should scale with that rather than the image.  Also, design decided that we should use 152px as the width.
before:
after:
> update(Row, CardContent): Add `minHeight` support. Add `small` image option. Rework CardContent before/after images and increase default size.

- packages/core/src/components/Tabs/index.tsx
- packages/core/test/components/Tabs.test.tsx
Remake of https://github.com/airbnb/lunar/pull/194 since Happo is broken.
> fix(Tabs): Listen for `popstate` on window instead of document. 

- packages/core/src/components/MessageItem/index.tsx
- packages/core/src/components/MessageItem/story.tsx
Wrap long titles, instead of squishing everything on one line.
A few use cases where the message item is in a small column, with large titles. The title is important to the message, so disabling truncation. Wrapping tag, time, and source as needed if there's a long title.
storybook at various widths
added a new story with all of the things for debugging
before with grid for title:
after with flex wrapping:
> update(MessageItem): Wrap long titles.

- packages/core/src/components/DataTable/columns/renderDataColumns.tsx
- packages/core/src/components/DataTable/index.tsx
- packages/core/src/components/DataTable/story.tsx
- packages/core/src/components/DataTable/types.ts
- packages/core/test/components/DataTable.test.tsx
Minor changes to some types so that the `rowData` property can be properly typed. This assumes the same shape for all renderers.
Unknown is too restrictive.
> types(DataTable): Update Renderer data shape to allow generics.

- packages/apollo/src/index.ts
Add typeDefs to Apollo settings so we can define the types for local data.
typeDefs example: https://www.apollographql.com/docs/react/data/local-state/#client-side-schema
See above!
Suggestions welcome
> update(Apollo): Add typeDefs to Apollo settings

- packages/forms/src/components/Form/story.tsx
- packages/forms/src/components/FormActions/index.tsx
Tried using FormActions exported from the form package within a Form. Got `Cannot add property disabled, object is not extensible`. Error. Cannot use `Object.assign` on `props`. Updated the story to use the FormActions from the form package, not the core version.
locally and in storybook
imported the FormActions from the form package into the form story to reproduce the error:
> fix(FormActions): Fix FormActions error `Cannot add property disabled, object is not extensible`.

- packages/core/src/components/Tabs/Tab.tsx
- packages/core/src/components/Tabs/index.tsx
- packages/core/src/components/Tabs/story.tsx
- packages/core/src/themes/buildTheme.ts
- packages/core/test/components/Tab.test.tsx
- packages/core/test/components/Tabs.test.tsx
@adamirl 
`<Tabs secondary>`
Alternate tab style
2 unit tests
> new(Tabs): Add `secondary` prop and styles.

- packages/core/src/components/DataTable/index.tsx
to: @milesj @stefhatcher @schillerk 
This adds back a 100% width style to `DataTable` cells that was removed [here](https://github.com/airbnb/lunar/pull/173/files#diff-e7a1b99de444068e45a6cc8b0c4fe2c9L466).
This is needed if consumers need 100% width cell content, it's not possible to override without hacking css selector style overrides in `withStyles` (i.e., a cell renderer cannot set its own `width: '100%'` to fix it).
Didn't see any visual difference with examples with vs without this style.
> fix(DataTable): Add back 100% width cell style.

- packages/core/src/components/DataTable/index.tsx
- packages/core/test/components/DataTable.test.tsx
to: @milesj @stefhatcher @schillerk 
This adds back the `propagateRef` prop which was deleted [here](https://github.com/airbnb/lunar/pull/173/files#diff-e7a1b99de444068e45a6cc8b0c4fe2c9L411), and fixed the test for it which clearly did not work 😛 . 
Don't break things.
NA
> fix(DataTable): Add back `propagateRef` prop.

- packages/core/src/components/NotchedBox/index.tsx
Currently, the default color is a light grey. For better contrast and theme consistency, updating to `color.accent.bg`.
- story
> update(NotchedBox): Update default background color to `color.accent.bg`.

- packages/core/src/components/Dropdown/index.tsx
withStyles passes in styles, and we do not omit it before passing props into the cx function.  For some reason this breaks dropdown on styleguide, because of some weirdness around them editing function prototypes.  
Styleguide has some library that adds something weird to function prototypes, that cause circular reference to themselves, and the prefix function in aphrodite breaks on a circular reference.  Fixing this is the easiest way to fix that.  And it is a bug we are passing it in anyways.
CI
> fix(Dropdown): Omit styles from props before passing into cx

- packages/core/src/components/DataTable/columns/renderSelectableColumn.tsx
- packages/core/src/components/DataTable/constants.tsx
- packages/core/src/components/DataTable/story.tsx
In https://github.com/airbnb/lunar/commit/ed2b890250774c808d304afa760c8e3576b09775#diff-f4d5288f4170d90e1c9824f8504fd651
I messed up spacing for expanded rows by adding `all`. This is a quick fix to re-enable additional left margin.
> style(DataTable): Adjust expanded row spacing.

- packages/core/src/components/Accordion/Item.tsx
- packages/core/src/components/Accordion/index.tsx
Remove background of `Accordion` and `AccordionItem`. This makes the background transparent.
Want to be able to specify background color for accordions.
Manual testing in style guide. No visual changes were found or expected.
No change. Should be verified via happo as well.
> style(Accordion, AccordionItem): Remove accordion background color.

- packages/core/src/components/DataTable/ColumnLabels.tsx
- packages/core/src/components/DataTable/story.tsx
This functionality is required by several apps, but totally broken right now and very difficult to hack around since `columnToLabel` only gives you access to the header content, but not the arrows.
Before
After
> fix(DataTable): Enable rightAlign functionality in columnMetadata.

- packages/core/src/components/Alert/index.tsx
Seeing an issue with Alert nested in various flex and block level displays, mixed with a long character titles, the Alert is overflowing outside of its container. Adding `word-break: break-word` helps the title to wrap better in these cases.
bug
locally with storybook
before:
after:
> fix(Alert): Add word-break support for titles.

- packages/core/src/components/MessageItem/index.tsx
- packages/core/test/components/MessageItem.test.tsx
bug fix and small cleanup
seeing an issue where when `loadingAuthor` is true, the content isn't wrapping the same as when loading is complete. with a small refactor, the layout and wrapping is the same regardless of author loading or not.
bug:
after:
> fix(MessageItem): Fix wrapping when author is loading.

- packages/core/src/components/DataTable/DataTable.tsx
- packages/core/src/components/DataTable/helpers/sortData.ts
- packages/core/src/components/DataTable/story.tsx
- packages/core/src/components/DataTable/types.ts
- packages/core/test/components/DataTable.test.tsx
to: @milesj @stefhatcher
cc: @schillerk 
tl;dr **`DataTable` sorting + expanded rows are incompatible** in some cases
Currently `sortBy` values are static in `DataTable`, meaning that you cannot dynamically change the value used to determine the sort order of a cell. We have use cases where the value of a cell changes dynamically (without a `data` update), which should result in a new sort order.
The current options for updating the sort are either 
a) pass new `data` to the table with the column value 
b) handle sort in the parent with `sortOverride`, which also requires new `data`. 
The primary issue we've encountered with new `data` is that is clears expanded + selected rows (this is even more problematic when `dynamicRowHeight` is used). This (again) makes sorting + expanded rows …
> new(DataTable): Add `sortByValue` accessor + `sortByCacheKey`

- packages/core/src/components/Table/index.tsx
- packages/core/src/components/Table/story.tsx
- packages/core/test/components/Table.test.tsx
Add a flag to disable the responsive wrapper div's overflow rules.
When I was rendering menus in my table, I was seeing overflow and clipping when these styles were enabled.
Added a unit test that assets against rendered classnames.
[See Slack thread]
> update(Table): Add `noWrap` prop.

- packages/core/src/components/MenuToggle/index.tsx
- packages/core/src/components/MenuToggle/story.tsx
- packages/core/test/components/MenuToggle.test.tsx
adds `muted` to change the button to a secondary, muted button.
seeing it pop up in a few designs.
storybook
> new(MenuToggle): Add muted menu option.

- packages/core/src/components/DataTable/DataTable.tsx
- packages/core/src/components/DataTable/story.tsx
- packages/core/src/components/DataTable/types.ts
to: @milesj @stefhatcher 
cc: @schillerk 
This PR fixes another issue with dynamic row height + sorting 😭 The cell measure cache should be invalidated on sort change when `dynamicRowHeight` is used, otherwise you can end up with invalid row heights (see images below).
This just adds an additional check in `componentDidUpdate` to clear the cache if sorts were changed, and updates the story to demonstrate that it works.
**Before**
(note the extra large row on top + clipped expanded row on bottom when the sort key is changed)
**After**
> fix(DataTable): Clear CellMeasureCache on sort change

- packages/core/src/components/AdaptiveGrid/index.tsx
- packages/core/src/components/AdaptiveGrid/story.tsx
to: @milesj @stefhatcher @hayes @alecklandgraf @schillerk 
Grid items that rendered null (for whatever reason) would render an empty block. This PR adds some logic to filter them out.
Cause it looks broken.
Storybook. This isn't testable since it's a CSS visual change.
Before:
After:
> fix(AdaptiveGrid): Hide/filter out empty grid items.

- packages/core/src/components/FormField/index.tsx
- packages/core/src/components/FormField/partitionFieldProps.ts
- packages/core/src/components/FormField/story.tsx
This updates the `FormField` to properly support small and large (which was missing).
During the `compact` -> `small` transition, the form field labels were not migrated, which is causing normal sized (15px) labels to be used for small inputs.
Storybook.
> new(FormField): Support small and large sizes.

- packages/core/src/components/ButtonGroup/index.tsx
- packages/core/src/components/ButtonGroup/story.tsx
- packages/core/src/components/ButtonGroup/styles.ts
- packages/core/src/components/Table/styles.ts
- packages/core/test/components/ButtonGroup.test.tsx
new `endAlign` prop to move buttons to `flex-end` / right side.
sometimes, we want buttons aligned to the end! especially in modals and workflows.
local storybook
tests
> new(ButtonGroup): Add `endAlign` support.

- packages/core/src/components/List/index.tsx
- packages/core/src/components/List/story.tsx
- packages/core/src/components/List/styles.ts
- packages/core/test/components/List.test.tsx
vertically center horizontal list items
sometimes height vary!
local storybook
new story
> new(List): Add `middleAlign` support for `horizontal`.

- packages/core/src/components/Tabs/styles.ts
Tabs component background color transparent
Tabs background is white. When component background is not white, tab looks off because the background colors don't match. To resolve this, make background tab color transparent. 
> update(Tab): Set background color to clear

- packages/core/src/components/Tabs/styles.ts
Tabs component background color transparent.
Tabs background is white. When component background is not white, tab looks off because the background colors don't match. To resolve this, make background tab color transparent.
Submitted a PR earlier to address this, but made the wrong component background transparent. This PR reverts that change and makes the button transparent. 
Verified with Storyboard:
Before:
After:
> update(Tab): Set Tab button background color to clear 

- packages/layouts/src/components/Layout/index.tsx
- packages/layouts/src/components/Layout/story.tsx
- packages/layouts/src/components/Layout/styles.ts
be able to adjust the min-height
sometimes, there's a top bar above the layout. need to adjust the min-height on layout to be something different besides `100vh`.
storybook
> new(Layout): Add custom `minHeight` support.

- packages/core/src/components/Accordion/Item.tsx
- packages/core/src/components/Accordion/index.tsx
- packages/core/src/components/Accordion/story.tsx
- packages/core/test/components/Accordion.test.tsx
add an option to break the default ux of an accordion - allow multiple to be open/toggled, instead of only one open at a time.
people want it and keep designing for it
storybook
tests
> new(Accordion): Enable multiple items to be open at once.

- packages/core/src/components/Card/Content.tsx
- packages/core/src/components/Card/story.tsx
- packages/core/src/components/Card/styles.ts
- packages/core/test/components/Card/Content.test.tsx
reopening  #248 as a direct PR instead of a fork.
Adding full size props for before/after to remove automatic spacing in the content.
There's been some churn in using before/after card content, first with us needing a new size for the content, and now us needing to make the image a link.  Making the content a bit more flexible so we can customize it as needed.
Checking in storybook.
> update(CardContent): Make before/after images clickable

- packages/core/src/components/DataTable/DataTable.tsx
- packages/core/src/components/DataTable/types.ts
- packages/core/test/components/DataTable.test.tsx
to: @milesj @stefhatcher @conglei @schillerk 
This simply exposes the `react-virtualized` `overscanRowCount` prop in the `DataTable` component.
We have a case where we'd like to change the `overscanRowCount` prop for performance optimization, but currently this prop is not exposed.
N/A
> new(DataTable): Expose `overscanRowCount` prop

- packages/core/src/components/Tooltip/index.tsx
- packages/core/src/themes/buildTheme.ts
- packages/core/test/components/__snapshots__/Tooltip.test.tsx.snap
to: @milesj @stefhatcher @lencioni @etr2460
We've been trying to do some perf optimization in a data-rich app, and noticed that the `left: -9999` style from `pattern.offset` used by `Tooltip` creates a very large layer which can become expensive for transitions and memory usage.
This PR makes a couple updates to help fix this
- update `pattern.offset` to be `left: -5vw` instead of `-9999px` to reduce its size
- render the persistent offscreen `a11y` tooltip content inside a `<Portal />` so that no matter its size it doesn't affect the flow of the content `<Tooltip />` wraps / is applied to 
- updates a `ref.getBoundingClientRect()` call to be within a `requestAnimationFrame` callback because it for [forces layout/reflow](https://gist.github.com/paulirish/5d52fb081b3570c81e3a#box-metrics) …
> update(Tooltip): Reduce offscreen pattern layer size and render a11y content in Portal

- packages/core/src/components/private/FormInput.tsx
Before:
After:
It was broken.
Storybook.
Above.
> fix: Fix proofreader crashing by memoizing form input.

- packages/layouts/src/components/Layout/index.tsx
- packages/layouts/src/components/Layout/story.tsx
- packages/layouts/src/components/Layout/styles.ts
- packages/layouts/test/components/Layout.test.tsx
towards https://github.com/airbnb/lunar/issues/267
> Right now non-fluid layouts have a max width, but there's no way to center the layouts on the screen. There should be a center prop on the layout that adds margin: auto on the container so that it is visually centered.
centering main content is nice
- added a story
- added a test
default:
with `centerAlign`:
> new(Layout): Add `centerAlign` prop to layouts.

- packages/core/src/components/Overlay/index.tsx
- packages/core/src/components/Tooltip/index.tsx
- packages/core/test/components/__snapshots__/Tooltip.test.tsx.snap
cc: @gaarf @lencioni @williaster 
Profiling found forced reflows from Tooltip and Overlay. It's hard to say how this affects load, but profiling this causes more layout renders than necessary during page load. My guess is in the order of 0.5 to 1 seconds could be saved based on reported render times. 
Here's a list of what will cause reflows: https://gist.github.com/paulirish/5d52fb081b3570c81e3a
**With a 6x CPU throttle about 10% of the page load is rendering.** 
**Here's what one reflow looks like from Tooltip**
Defers calculating page layout via a requestAnimationFrame or until the layout calc is required for rendering.
I will update tests after I reproduce this locally in lunar local dev. 
N/A
- My code follows the style guide of this …
> fix(Tooltip, Overlay): Fix reflows on cDM, cDU, and render

- packages/core/src/components/private/BaseTextArea.tsx
The BaseTextArea's componentDidMount is causing some layout thrashing. This wraps the reflow in a requestAnimationFrame.
Profiling
Tests pass 🤞 
Storybook worked
> fix(TextArea): Wrap reflow in requestAnimationFrame

- packages/core/src/components/Tooltip/index.tsx
- packages/core/test/components/Tooltip.test.tsx
to: @milesj @stefhatcher @hayes @alecklandgraf @gaarf 
The `Tooltip` can render for one frame at position `0, 0` while `state.targetRect` is being asynchronously set from `componentDidMount` 
Prevent a UI regression.
Storybook and existing tests. 
Can log the `state.targetRect` to see its values at render time
**before**
N/A
> fix(Tooltip): Prevent tooltip from rendering at 0, 0

- packages/core/src/components/Modal/private/Inner.tsx
- packages/core/test/components/Modal.test.tsx
Keeps the modal open when clicking outside.
We need this functionality. Somewhat related to: https://github.com/airbnb/lunar/issues/273
Unit tests.
N/A
> new(Modal): Add `persistOnOutsideClick` prop.

- packages/apollo/src/index.ts
- packages/apollo/test/index.test.ts
Allow callers of `Apollo.initialize` to specify an optional `cacheConfig`
Allows consumers to specify their unique (fragment matching, type policies, etc)
Updated the unit tests around `Apollo.initialize`
> update(Apollo): Expose cacheConfig

- packages/core/src/components/HierarchyPicker/Hierarchy/HierarchyItem.tsx
- packages/core/src/components/HierarchyPicker/Hierarchy/HierarchyList.tsx
- packages/core/src/components/HierarchyPicker/Hierarchy/index.tsx
- packages/core/src/components/HierarchyPicker/Picker/index.tsx
- packages/core/src/components/HierarchyPicker/Search/index.tsx
- packages/core/src/components/HierarchyPicker/story.tsx
- packages/core/src/components/HierarchyPicker/types.ts
- packages/core/test/components/HierarchyPicker/Hierarchy.test.tsx
- packages/core/test/components/HierarchyPicker/Picker.test.tsx
- packages/core/test/components/HierarchyPicker/Search.test.tsx
Passes the current item/node object as the 2nd argument to `onItemPicked`. The previous 2nd argument is shifted to the 3rd argument (this only exists for legacy usage).
We need a simple way to access the ID or other metadata for the item being selected. Previously, we only passes the path as an array, which required us to manually walk the tree each time. This change will mitigate that.
Unit tests and storybook.
N/A
> update(HierarchyPicker): Pass the current item object to `onItemPicked`.

- packages/core/src/components/Autocomplete/index.tsx
- packages/core/src/components/Autocomplete/story.tsx
- packages/core/src/components/Multicomplete/index.tsx
- packages/core/src/components/Multicomplete/story.tsx
- packages/core/test/components/Autocomplete.test.tsx
Adds a new prop that allows the value in the input field to be selected if its not in the loaded items list.
We needed a system that allowed new "tags" to be added to an object. The tag can either be an existing tag (from the autocomplete), or a new one (when submitted).
Unit tests and storybook.
> update(Autocomplete, Multicomplete): Add `selectUnknownOnEnter` prop.

- packages/core/src/components/Loadable/index.tsx
- packages/core/test/components/Loadable.test.tsx
- Adds a `mounted` check since the loading changes occur in a timeout, which may happen when the component is unmounted.
- Adds a `noSuspense` prop to remove the `Suspense` wrapper, so a higher level one can be used (for routers).
- Call `React.lazy` as close as possible to the module scope, and not during render, as this as how it should be used. Only applies to `factory()`.
Was causing massive thrashing on page load.
Pulled it locally into a project to verify changes work.
> update(Loadable): Fix layout thrashing and improve performance.

- packages/core/src/themes/dark.ts
previous reds were too...red and needed more contrast. thanks @adamirl 
storybook
> style: Update dark mode danger colors.

- packages/core/src/components/Overlay/index.tsx
- packages/core/test/components/Overlay.test.tsx
Fixes tooltips from rendering at 0,0. 
Tooltips are initially rendering at 0,0.
Updated tests. 
> fix(Overlay): Prevent Overlay from rendering at 0, 0

- packages/core/src/components/TextArea/Proofreader/index.tsx
- packages/core/src/components/TextArea/index.tsx
- packages/core/test/components/TextArea/Proofreader.test.tsx
Fix a case where `prevProps.value` is `undefined`.
Added test
n/a
> fix(Proofreader): Default prop value to empty string

- packages/core/src/components/MenuToggle/index.tsx
- packages/forms/src/components/FilterMenu/index.tsx
with the recent refactor of FilterMenu, the functionality of closing on apply broke. this fixes that!
help unblock a team from updating
storybook
tests still pass!
> fix(FilterMenu): Close dropdown after filters are applied.

- packages/core/src/components/FormActions/index.tsx
- packages/core/src/components/FormActions/story.tsx
- packages/core/test/components/FormActions.test.tsx
adds a `block`prop, to render FormActions buttons full width
sometimes, you want a submit button that's full width! cancel/reset stack with `block` enabled
storybook
tests
> new(FormActions): Add `block` option to buttons.

- .gitignore
- package.json
- packages/composer/src/components/Actions/ActionButton.tsx
- packages/composer/src/components/Actions/index.tsx
- packages/composer/src/components/Emojis/EmojiButton.tsx
- packages/composer/src/components/Input/InlineInput.tsx
- packages/composer/src/components/Input/index.tsx
- packages/composer/src/components/Preview/Window.tsx
- packages/composer/src/components/Preview/index.tsx
- packages/composer/src/components/Shortcuts.tsx
- packages/composer/src/components/Suggestions.tsx
- packages/composer/src/helpers/actions.ts
- packages/core/src/components/DataTable/TableHeader.tsx
- packages/core/src/components/DataTable/story.tsx
- packages/core/src/components/ImageViewer/RotateControls.tsx
- packages/core/src/components/ImageViewer/ZoomControls.tsx
- packages/core/src/components/Lightbox/Header.tsx
- packages/core/src/components/Pagination/index.tsx
- packages/core/src/components/Pagination/story.tsx
- packages/core/src/components/Proofreader/helpers.ts
- packages/core/src/components/Translate/story.tsx
- packages/core/src/utils/getLanguageFromLocale.ts
- packages/core/src/utils/getMemberName.ts
- packages/core/test/components/Lightbox/Header.test.tsx
- packages/forms/src/components/FeedbackForm/index.tsx
- packages/forms/src/components/FilterMenu/index.tsx
- scripts/tasks/extractPhrases.ts
Updates all our translations to have a key that starts with `lunar.`. Also wrote a script to extract them all.
We're gonna localize this soon.
Locally.
Example output:
```json
[
{
"key": "lunar.common.apply",
"phrase": "Apply",
"contexts": [
"This button applies all live edits.",
"Apply filters button label"
]
},
{
"key": "lunar.common.cancel",
"phrase": "Cancel",
"contexts": [
"This button cancels out of edit mode without applying changes.",
"Button label to cancel a form action"
]
},
{
"key": "lunar.common.close",
"phrase": "Close",
"contexts": [
"Close the alert",
"Close a sheet popup",
"Close a toast popup",
"Close a modal popup"
]
},
{
"key": "lunar.common.collapse",
"phrase": "Collapse",
"contexts": [
"Collapse"
]
},
]
```
- My code …
> fix: Update phrase keys and add extraction script.

- packages/composer/package.json
- packages/composer/src/Composer.story.tsx
- packages/composer/src/components/Composer.tsx
- packages/composer/src/components/Footer/index.tsx
- packages/composer/src/components/Input/index.tsx
- packages/composer/src/components/Menu/index.tsx
- packages/composer/src/components/Preview/index.tsx
- packages/composer/src/contexts/ComposerContext.ts
- packages/composer/src/helpers/hotkeys.ts
- packages/composer/src/helpers/shortcuts.ts
- packages/composer/src/types.ts
- packages/composer/test/components/Composer.test.tsx
- packages/composer/test/components/Footer.test.tsx
- packages/composer/test/mocks.tsx
Title.
Some people don't like `shift+enter` to submit, so allow them to submit using just `enter`.
Storybook.
> update: Add `submitOnEnter` prop and hotkey negation.

- packages/composer/src/components/Shortcuts.tsx
- packages/composer/test/components/Composer.test.tsx
Switches from `enter` to `tab`.
Relying on enter interferes with using enter to submit the form. So switching to tab, which aligns with the way suggestions are selected.
Yes
> fix: Use tab instead of enter for shortcut selection.

- packages/core/src/components/ProgressBar/index.tsx
- packages/core/src/components/ProgressBar/story.tsx
- packages/core/src/components/ProgressBar/styles.ts
- packages/core/test/components/ProgressBar.test.tsx
cc: @williaster 
adds status color options to progress bar, based off of colors in StatusText:
- danger
- muted
- notice
- success
- warning
request and the options are helpful
storybook
unit tests
> new(ProgressBar): Add status color options.

- packages/core/src/components/Tooltip/index.tsx
- packages/core/src/components/Tooltip/story.tsx
- packages/core/src/components/Tooltip/styles.ts
- packages/core/test/components/__snapshots__/Tooltip.test.tsx.snap
Currently the text alignment of `Tooltip` content matches however the `Tooltip` popover is positioned (left, center, right). Because of this we **always** have to set `<Text startAlign>{...}</Text>` for our tooltip content to override the behavior and have consistent styles. After talking offline we agreed this wasn't really needed.
This updates the `Tooltip` component styles to _not_ affect the text alignment of the `Tooltip` content itself. `textAlign` is set on the `Tooltip` container and is needed to correctly position the popover (removing this entirely breaks right positioning).
_Note_: you can still obviously override the alignment by wrapping in a `<Text endAlign/centerAlign>` etc.
**Before**
**After**
- My code follows the style …
> fix(Tooltip): Don't set text alignment of Tooltip content

- packages/core/src/components/Card/Content.tsx
- packages/core/src/components/Card/private/Side.tsx
- packages/core/src/components/Card/story.tsx
- packages/core/src/components/Card/styles.ts
- packages/core/test/components/Card/Content.test.tsx
making the card content more flexible and generalized.
updated examples to show how images can be used in before/after/top props.
- Removed:
- `afterImageSrc`
- `beforeImageSrc`
- `small`
- `large`
- New:
- `noPaddingAfter` to do full cover after content
- `noPaddingBefore` to do full cover before content
- `noPaddingTop` to do full cover top content
- Generalized:
- `topImageSrc` -> `top` (string to node)
- `onAfterImageClick` -> `onAfterClick`
- `onBeforeImageClick` -> `onBeforeClick`
small before image
```jsx
// before
<Card>
<Content small beforeImageSrc="moon.jpg">
Moon
</Content>
</Card>
// after
<Card>
<Content
noPaddingBefore
before={<Image background cover alt="" height="100%" width={80} src="moon.jpg" />}
>
Moon
</Content>
</Card> …
```
> breaking(CardContent): Consolidate before/after props. Remove afterImageSrc, beforeImageSrc, small, and large props. Generalize other props.

- packages/core/src/components/CheckBox/index.tsx
- packages/core/src/components/CheckBox/story.tsx
- packages/core/src/components/FormField/index.tsx
- packages/core/src/components/FormField/styles.ts
- packages/core/src/components/RadioButton/index.tsx
- packages/core/src/components/RadioButton/story.tsx
- packages/core/src/components/private/BaseCheckBox.tsx
- packages/core/src/components/private/BaseRadioButton.tsx
- packages/forms/src/components/Form/story.tsx
- For `CheckBox` and `RadioButton`, default to top alignment instead of middle alignment
new ui default
storybook
> breaking(CheckBox, FormField, RadioButton): Remove topAlign and default to top alignment. Add middleAlign option.

- packages/core/src/components/Timeline/Item.tsx
- packages/core/src/components/Timeline/index.tsx
- packages/core/src/components/Timeline/story.tsx
- Import path for `IconRecord` was incorrect - works locally and in storybook but not when consuming the npm package
- Exported `Timeline/Item` from index. This seems to confuse Storybook and the props for `Timeline/Item` are shown when viewing `Timeline` itself.
- **Disable happo for `Timeline` component**, see: https://github.com/airbnb/lunar/pull/327#issuecomment-591682052
Can't use `Timeline` without `IconRecord` import change
Local storybook
No visual change
> fix(Timeline): Correctly import IconRecord and export Timeline/Item

- packages/layouts/src/components/Aside/index.tsx
- packages/layouts/src/components/Aside/story.tsx
- packages/layouts/test/components/Aside.test.tsx
Adds an `expanded` prop.
We need to be able to control the expanded state externally, so this provides a hook to.
Yes, jest and storybook.
Happo.
> update(Aside): Add external expanded support.

- packages/core/src/components/Tabs/index.tsx
- packages/core/src/components/Tabs/story.tsx
- packages/core/test/components/Tabs.test.tsx
add a new optional `onPushState` prop to `<Tabs />` to be used in conjunction with `persistWithHash`.
One may want to use _react-router_'s `pushState` instead of the native one.
Added to existing spec
n/a
> update(Tabs): Add onPushState prop

- packages/core/src/components/DataTable/ColumnLabels.tsx
- packages/core/src/components/DataTable/columns/renderDataColumns.tsx
- packages/core/src/components/DataTable/columns/renderExpandableColumn.tsx
- packages/core/src/components/DataTable/constants.tsx
Removing padding from the first and last columns of DataTable. They were inconsistent with @kenchendesign's mocks, and required negative margins to correct against, which is super messy.
> update(DataTable): Reduce padding for first/last column.

- packages/core/src/components/Row/index.tsx
- packages/core/src/components/Row/story.tsx
- packages/core/src/components/Row/styles.ts
Discussed in Lunar Project Planning (see agenda).
With compact and inline both enabled, before/after padding down to 0.5 * unit.
With inline enabled, no vertical padding.
> update(Row): Reduce padding for inline and compact.

- packages/core/src/components/Tooltip/index.tsx
- packages/core/src/components/Tooltip/story.tsx
Add an `align` prop that allows overriding the default calculated align value.
Also organized the props alphabetically.
Request from design for Torch app.
Local
> update(Tooltip): Add `horizontalAlign` and `verticalAlign` props.

- packages/core/src/components/Tooltip/index.tsx
- packages/core/src/components/Tooltip/story.tsx
Add `toggleOnClick` prop that toggles the display of the tooltip content on user click when true.
Request from design
Local
> update(Tooltip): Add `toggleOnClick`  prop.

- packages/core/src/components/Proofreader/Renderer.tsx
when pasting large text that included matchers like links, pressing enter, expanding the height of the textarea, this weirdness would happen:
fix:
broken experience for our proofreader and consumers
storybook
> fix(TextArea, Proofreader): Fix double link render.

- packages/core/src/components/Proofreader/ControlBar.tsx
- packages/core/src/components/Proofreader/LocaleMenu.tsx
- packages/core/src/components/Proofreader/index.tsx
- packages/core/src/components/Proofreader/types.ts
- packages/core/src/components/TextArea/story.tsx
the language list can be long, and sometimes flow off screen
helpful to be able to set a max height on the menu and make it scrollable
local storybook
> update(Proofreader): Add max height prop for locale menu.

- packages/core/src/components/BrowserNotification/index.tsx
- packages/core/src/components/ScrollSection/ScrollWrapper.tsx
- packages/core/src/crosstab.ts
Lazy-loads `BroadcastChannel` as crosstab is a side-effect and the channel does not exist in some browsers, nor in SSR, so it crashes. This turns it into a no-op in those cases.
Also added checks in some other locations.
More SSR work.
> fix: Lazy-load `BroadcastChannel`.

- packages/core/src/components/GradientScroller/index.tsx
- packages/core/src/components/GradientScroller/story.tsx
- packages/core/src/components/Tabs/story.tsx
- packages/core/test/components/__snapshots__/GradientScroller.test.tsx.snap
When using `<GradientScrollbar showArrows />`, if the content does _not_ overflow, we would see a flash of the arrow before the ResizeObserver does it's thing.
StyleBook
before this change, in nova usage of `<Tabs scrollable />` :
> fix(GradientScroller): Initially hide gradient end.

- packages/core/src/components/TrackingBoundary/index.tsx
- packages/core/src/themes/global.ts
- packages/core/test/components/TrackingBoundary.test.tsx
- types/global.d.ts
Migrates from a custom element to a `div`, as the former does not work in SSR. This shouldn't break anything as the former was also display block.
Support SSR.
N/A
> fix(TrackingBoundary): Update element to a `div`.

- packages/icons/src/index.ts
This crashes some bundlers as the `main` field in `package.json` is pointing to a non-existent file.
Fix the bundlers.
> fix: Add index file to resolve imports.

- packages/core/src/components/HierarchyPicker/Search/index.tsx
In Torch we are hitting this issue: https://github.com/krisk/Fuse/issues/357  via `Search` in `HierarchyPicker` . Apparently this breaking change was added as part of a minor upgrade to Fuse, and was fixed here: https://github.com/krisk/Fuse/commit/1b921e29a78fdaae5524b27c36b3b702ff19d7d7 .  Rather than attempting to upgrade the package, this PR scales the key weights such that they sum to 1. I rounded the numbers a bit to make things more clear, but can add some more precision if necessary.
Problem outlined above.
Locally
N / A
> fix(HierarchyPicker): Scale weights to sum to 1

- packages/core/src/crosstab.ts
- packages/core/test/crosstab.test.ts
`crosstab` was creating new BroadcastChannels at each `on`, `off`, and `emit` method call. 
Crosstab wasn't working as expected after the previous change. 
Added test
N/A
> fix(crosstab): Create one channel per instance

- packages/core/src/components/Tooltip/index.tsx
- packages/core/src/components/Tooltip/story.tsx
cc @avand @stopachka
This PR adds an optional `accessibilityLabel` prop to the `Tooltip`, mostly to enable an opt-in (non-breaking) perf improvement. 
Currently the `content` prop of `Tooltip` is rendered in an invisible `Portal` for a11y, to serve as an `aria-labeledby` element that is rendered whether or not the `Tooltip` popup is visible. This can lead to performance issues on pages with 100s of `Tooltips` as `content` is rendered at all times.
We discussed that one solution to ensure accessibility but allow for optimization is to override this behavior by specifying an `aria-label` (`accessibilityLabel` prop) to be used instead. 
Note: there was some discussion about whether omission of `aria-labelledby`/duplication of content should be …
> new(Tooltip): Add optional accessibilityLabel for perf

- packages/core/src/components/TermList/Term.tsx
- packages/core/src/components/TermList/story.tsx
to: @milesj @schillerk 
noticed the `large` text prop wasn't working. fix for that. updated the stories to show usage of text properties!
more people are starting to use this, seeing key/value pair lists in designs more.
- storybook
> fix(Term): Fix `large` prop conflicting with `small` default. Update stories.

- packages/core/src/components/Modal/private/Inner.tsx
- packages/core/src/components/Modal/private/InnerContent.tsx
- packages/core/src/components/Modal/story.tsx
- packages/core/src/components/Modal/styles.ts
- packages/core/test/components/Modal.test.tsx
new top bar request from design. can put whatever in it! has a border on the bottom with an option to center align (through text-align) the content. works independent of title/subtitle/header.
design needs
storybook
> new(Modal): Add `topBar` and `topBarCentered` support.

- packages/core/src/components/ErrorMessage/index.tsx
- packages/core/src/types.ts
- packages/core/test/components/ErrorMessage.test.tsx
Check for the presence of properties on `Error` objects instead of gating by type (`instanceof Error`).
`APIError` instances (`error instanceof Error === true`) _do_ have additional properties on them which can be used to render more information in the `ErrorMessage` component. Let's use them.
Added/updated tests. Ran storybook locally.
N/A
> update(ErrorMessage): Handle error object props more robustly.

- packages/core/src/components/ErrorMessage/index.tsx
- packages/core/src/components/ErrorMessage/story.tsx
- packages/core/src/index.ts
- packages/core/src/types.ts
- packages/core/test/components/ErrorMessage.test.tsx
- Add `traceURL` setting
- Use `trace_id` property from `ErrorMessage` for link for more info on that trace ID
- Update the `Button` to a `Link` (no need for it to be a button that I can think of - don't need to generate the URL "on the fly" when the button is clicked, we can use a plain anchor tag)
Allow better debugging when a `trace_id` is present in an `Error` passed to `ErrorMessage` component.
Added tests. Ran `sg` locally and verified.
> update(ErrorMessage): Add trace ID link

- packages/core/src/components/DataTable/ColumnLabels.tsx
cc @schillerk 
Fixes an issue with DataTable where [this commit](https://github.com/airbnb/lunar/commit/1db54a9cd9b6850f2fca7f2d71e6cf174333707b#diff-8cd6767ced5d1ee6e96c679cc4d680f6R77) casts `undefined` to a `string` which `react-virtualized` interprets as needing a sortable column. This breaks styles for any table that is expandable or selectable.
See above.
**Before**
(note the sortable `undefined` in the first column)
**After**
> fix(DataTable): Don't cast undefined to a string

- packages/core/src/components/DatePicker/index.tsx
- packages/core/src/components/DatePicker/story.tsx
- packages/core/src/components/DatePickerInput/index.tsx
- packages/core/src/components/DateTime/index.tsx
- packages/core/src/components/DateTime/story.tsx
- packages/core/src/components/DateTimeRange/index.tsx
- packages/core/src/components/DateTimeRange/story.tsx
- packages/core/src/components/DateTimeSelect/index.tsx
- packages/core/src/components/DateTimeSelect/story.tsx
- packages/core/src/components/Price/index.tsx
- packages/core/src/components/Price/story.tsx
- packages/core/src/components/PriceComparison/index.tsx
- packages/core/src/components/PriceComparison/story.tsx
- packages/core/src/components/PriceGroup/index.tsx
- packages/core/src/components/PriceGroup/story.tsx
- packages/core/src/utils/createDateTime.ts
- packages/core/test/components/DateTime.test.tsx
- packages/core/test/components/DateTimeRange.test.tsx
- packages/core/test/components/Price.test.tsx
- packages/core/test/components/PriceComparison.test.tsx
- packages/core/test/components/PriceGroup.test.tsx
- packages/core/test/utils/createDateTime.test.ts
handle bad values like `"[Hidden]"` being added to things expected timestamps or numbers representing an amount.
caused components to crash
- storybook
- new tests
- old tests passing
> new(DateTime, DateTimeRange, DateTimeSelect, Price, PriceComparison, PriceGroup): Add empty fallback if an invalid value is provided.

- packages/core/src/components/DataTable/DataTable.tsx
- packages/core/src/components/DataTable/constants.tsx
- packages/core/src/components/DataTable/types.ts
- packages/core/test/components/DataTable.test.tsx
cc @schillerk 
This PR
- adds a new row size to `DataTable`: `xLarge`
- improves the `rowHeight` type from `string` to a union of possible `string`
- tries to fix some conditions which lead to infinite re-renders from `forceUpdate` calls in `componentDidUpdate`
I've been trying to upgrade to lunar v3 and some of our tables are pretty broken, especially for dynamic row height. Adding an additional fixed row height will alleviate some of these issues for us, and I'm hoping the `forceUpdate` logic may help. I'm not sure if there have been regressions, but it's pretty easy to generate a stack trace in the storybook now. Go [here](https://airbnb.io/lunar/?path=/story/core-datatable--a-table-with-dynamic-sort-key), expand the row, then sort a …
> new(DataTable): Add xLarge row size. Fix forceUpdate logic.

- packages/core/src/components/DataTable/DataTable.tsx
- packages/core/src/components/DataTable/constants.tsx
- packages/core/src/components/DataTable/types.ts
This fixes a remaining comment from #367, and updates `xLarge` => `xlarge` for consistency in `DataTable`s `rowHeight` options.
~I tried removing the logic to create a new `timeout` if one existed, just letting the existing one run, but it broke the dynamic updating so I think we should keep it as is.~ EDIT: got this to work. 
I also added a `clearTimeout` call on unmount.
See #367.
NA
> fix(DataTable): rowHeight xLarge => xlarge

- packages/core/src/components/Loader/styles.ts
Remove redundant spacing after the last dot, so loader can be align horizontal center accurately.
As description.
Verified it looks correct in storyboard.
> fix(Loader): remove redundant spacing

- packages/forms/package.json
- packages/forms/src/components/Form/index.tsx
- packages/forms/src/types.ts
- packages/forms/test/index.test.ts
- yarn.lock
In order to support dynamic forms in Tower, this PR adds the final form arrays plugin.
https://final-form.org/arrays
My current work requires a form that allows users to dynamically add and remove fields from a form. I've looked at different ways to solve this without modifications to lunar, but wasn't able to find anything that solved all my issues.
Looking for feedback here, I'm not sure what sort of testing is appropriate, since this is mostly a configuration change.
This PR doesn't affect any existing lunar components.
> new(Forms): Add support for arrays of fields.

- packages/forms/package.json
- yarn.lock
Somehow when I added final-form-arrays, the yarn lock entry was pointing to an internal registry. This fixes it to use the yarn registry.
The build was failing because the internal registry was unreachable.
CI
n/a
> fix(Forms): Correct yarn.lock entry for final-form-arrays

- packages/core/src/components/Breadcrumbs/Breadcrumb.tsx
- packages/core/src/components/Breadcrumbs/index.tsx
- packages/core/src/components/Breadcrumbs/styles.ts
- packages/core/src/components/List/index.tsx
- packages/core/src/components/List/story.tsx
- packages/core/src/components/List/styles.ts
- packages/core/test/components/List.test.tsx
Ran into a use case where it'd be handy to visually reverse the list, e.g. a list of facts ordered from most recent to oldest, needing to reverse that visually.
Also, fixed warning about adding `horizontal` onto `li`. Only apply that to `<Item>`s.
- new stories
- new tests
> new(List): Add reversed prop to visually reverse the list items.

- packages/forms/src/components/Form/index.tsx
- packages/forms/test/components/Form.test.tsx
This PR checks for an existing field value when a field is registered, and uses that value rather than the form initial value.
Using final form mutators, it's possible to set a field value before the initial mount of the component. I'm working on a form that uses [Final Form Arrays](
https://final-form.org/docs/final-form-arrays/getting-started) to arbitrary numbers of rows to a form. 
I've added a unit test that verifies the new behavior
> update(Forms): Use form values if present on register

- packages/core/src/components/Copy/index.tsx
- packages/core/src/components/Copy/story.tsx
- packages/core/test/components/Copy.test.tsx
cc: @etr2460 @kenchendesign 
This adds a hook to invert the color of the `Copy` tooltip.
We use `black` tooltips throughout our apps when they have instructional content. We can't make this consistent because the `Copy` `Tooltip` cannot currently be inverted.
Default
Inverted
> new(Copy): Add invertTooltip prop

- packages/core/src/components/Tooltip/index.tsx
- packages/core/src/components/Tooltip/story.tsx
- packages/core/src/components/Tooltip/styles.ts
- packages/core/test/components/Tooltip.test.tsx
A popover is essentially a tooltip component with the ability to persist the popup by mouse-entering the popup portion of the tooltip. 
This functionality is achieved by adding a delay timer and setTimeout (via `delaySetPopupVisible`) to ensure that the popup persists long enough for a mouse to move from tooltip trigger to popup div when the `popover` prop is selected. When a mouse enters the popup div, the timer is cleared, and the popup can persist until the mouse leaves the popup.
Several internal tools at Airbnb now require the ability to click links inside a popup, and copy-and-paste text in the popup. However, without this prop, it is not possible to interact with the contents of a popup in the Lunar tooltip
(`remainOnMouseDown` & …
> new(Tooltip): Add `popover` prop

- packages/core/src/components/ImageViewer/RotateControls.tsx
- packages/core/src/components/ImageViewer/ZoomControls.tsx
- packages/core/test/components/ImageViewer/RotateControls.test.tsx
- packages/core/test/components/ImageViewer/ZoomControls.test.tsx
title and diff should be explanatory
Design calls for icon sizes to be modifiable - the `<RotateControls />` and `<ZoomControls />` components almost always accompany `<ImageViewer />`, and if `<ImageViewer />` height/width can be changed via props, then naturally the controls should be too for extensibility. 
Updated tests to include size prop. 
n/a
> update(RotateControls, ZoomControls): Add icon size prop

- packages/core/src/components/Tooltip/styles.ts
- packages/core/src/themes/buildTheme.ts
- packages/core/src/themes/dark.ts
- packages/core/src/themes/light.ts
- packages/core/src/types.ts
When in dark mode, the inverted tooltip text isn't readable. This change fixes that, and also improves the accessibility of the colors for light mode.
In order to make this fix, ~I needed to have theme mode aware styles or use some other color from the theme; there were no applicable analogs, so I went the route of exposing the current theme mode in the theme.~ I added a new `baseInverse` color value to the theme.
The colors currently used for the inverted tooltip aren't accessible, causing difficulty for viewers of all eyesights
- Tested with storybook
**Light Mode**
Before | After
-|-
Notice how the transparency decreases the contrast, making it harder to read |
**Dark Mode**
Before | After
-|-
Notice how the text is almost completely unreadable |
- …
> update(tooltip): Make inverted text readable in dark mode

- packages/core/src/components/Tooltip/styles.ts
Turns out when I made my previous change #386, I didnt account for the fact that the text would always be the default color (which works well against `color.base`, but not so well for `color.baseInverted`).
Since the background will be `baseInverted`, this change sets the foreground color to `base` which, by definition will be contrasting
See above
No visual change for this project, it seems that the colors work well in lunar's storybook, but not for other projects like Nova.
> fix(tooltip): Set font color for inverted tooltip

- packages/core/src/components/Autocomplete/index.tsx
`BaseInput` in `Autocomplete` doesn't receive `hasPrefix` and `hasSuffix` props before, which would cause style bug with `<Prefix />` and `<Suffix />`.
The `hasPrefix` and `hasSuffix` condition check is copied from `partitionFieldProps()` function.
Fix style bug.
Looks good in storybook.
Before:
After:
> fix(Autocomplete): prefix and suffix style

- packages/core/src/components/Overlay/Portal/index.tsx
- packages/core/src/components/Overlay/Portal/styles.ts
- packages/core/src/components/Overlay/index.tsx
This PR adds the `enableMouseInteraction` prop to `Overlay` and `Overlay/Portal` to enable mouse events and mouse interaction in Overlays.  In the Overlay portal stylesheet, we extract the `container` class' `userSelect: 'none'` out into a `noUserSelect` class, and introduce the ~`hasPointerEvents`~ `withPointerEvents` class to explicitly enable pointer events in Overlay. These two classes are composed in such a way that there are no breaking changes. 
Overlay's portal implementation is useful for Tooltip and Popover popups, which need to escape their parent divs. The current Popover implementation renders the popup in a div with a set zIndex, which does not let the popup escape a DataTable row, while a plain Tooltip's `<Overlay></Overlay>` popup is able to …
> new(Overlay): Add `enableMouseInteraction` prop

- packages/core/src/components/Tooltip/index.tsx
- packages/core/src/components/Tooltip/story.tsx
- packages/core/src/components/Tooltip/styles.ts
This PR refactors Popover to render inside an `<Overlay>` component, just like the plain tooltip. It also moves the popup `mouseEnter` and `mouseLeave` handlers up to the popup content's outermost div.
Note: We'll want to land #391 first, and then update the target of this PR to master. I set the base of this PR to the Overlay PR to facilitate code review.
The original Popover component rendered in a simple div with a style of `zIndex:1`. This was naive on my part for several reasons: 
1. The Popover would need a much larger zIndex to escape divs with zIndexes potentially much larger than 1. 
2. In our Popover-inside-DataTable use case, the Popover was unable to escape a DataTable row, while a regular Tooltip, which rendered in Overlay's portal, was able to. …
> update(Tooltip): Render Popover's popup in Overlay component

- packages/core/src/components/DateTimeSelect/story.tsx
This story fails happo for nearly every PR because it "falls back to today's date" and is therefore nondeterministic.
Time is money 🤑 
CI
> docs(DateTimeSelect): Disable happo for non-deterministic story

- packages/core/src/components/FormField/styles.ts
This PR updates `compactSpacing` of the FormField styles from `16px` to `12px`, which is used for `CheckboxController` and `RadioButtonController` default spacing.
For `Checkboxes` and `RadioButtons`,  **16px** between each options looks good when there are subtitles, but is too spacious when there are no subtitles, and **12px** is just right and provides a nice compromise that works regardless of whether there are subtitles. 
And these changes are approved by the Lunar committee earlier this year  https://git.musta.ch/airbnb/solar/issues/875
Tested with local storybook. 
**Before (16px):**
**After (12px):**
**Before (16px with subtitles):**
**After (12px with subtitles):**
- I have updated or added …
> update(FormField): Update compact spacing in styles

- packages/core/src/components/Link/index.tsx
- packages/core/src/components/Link/story.tsx
- packages/core/src/components/Link/styles.ts
- packages/core/test/components/Link.test.tsx
This adds a `truncated` property to links and a `link_truncated` style, as well as a unit test. It also removes `truncated` from the `textProps` because it doesn't work.
Although Link takes in `textProps` to pass to the Text component, `overflow` and `text-overflow` aren't inherited, so the truncation isn't applied. This removes the ability to define `truncated` in the `textProps` and adds a prop to Link so that truncating a Link with ellipsis is possible.
I tested this locally in storyguide and added a unit test.
> update(Link): Add `truncated` prop

- packages/core/src/components/Card/index.tsx
- packages/core/src/components/Card/story.tsx
- packages/core/src/components/Card/styles.ts
- packages/core/test/components/Card.test.tsx
Add two new props for the `Card` component. 
1.  `noShadow` that hides the shadow of the card.
2. `selected` that shows the border when selected.
**Background:** 
Some discussions are here https://git.musta.ch/airbnb/solar/issues/978, the design team call out for adding a new variation '`noShadow`' for Card to support some features like the wrapper of checkboxes.
And in the long run, looks like the Lunar team also consider to refactor `clickable button checkboxes` to just being wrapped with `card`, so also adding the `selected` state here in this PR. 
**Design:** [figma](https://www.figma.com/file/JRX1IRigC6oxce2nyFqAZM/Nova-Guides---V2-Features?node-id=1016%3A64864)
Local storybook and unit tests. 
When there is **noShadow**: 
When **selected**: 
- My code …
> new(Card): Adding two props 'noShadow' and 'selected' for Card

- packages/core/src/components/ImageViewer/ZoomControls.tsx
- packages/core/src/components/ImageViewer/story.tsx
We have a use case in Torch to place the zoom controls at the bottom of the screen which results in the dropdown menu being cut off. Adding a prop to override this.
Above
Storybook
> update(ImageViewer): Add `dropdownAbove` prop

- packages/core/src/components/ImageViewer/index.tsx
`document.preventDefault` should only be called when `dragging` is `true`, otherwise it's impossible to highlight text and in the document
Running into this error in Torch
Tested locally in Storybook, added a text component above `<ImageViewer />`, tried to highlight and it didn't work. After this change, highlighting worked.
No visual diff
> fix(ImageViewer): Only call document.preventDefault() when dragging

- packages/core/src/components/Modal/private/Inner.tsx
- packages/core/test/components/Modal.test.tsx
Refactor `ModalInner` component into functional component with hooks.
Currently, the `innerStyleSheet` prop of `Modal` is not working, because `ModalInner` not support customized stylesheet. In order to support it, we need to refactor `ModalInner` component into functional component with hooks.
- All unit test case passed
- Manually test `Modal` component in storybook and all work fine
There is no UI change.
> update(ModalInner): refactor with hooks

- packages/core/src/components/Lightbox/index.tsx
- packages/core/src/components/Lightbox/styles.ts
- packages/core/src/constants.ts
This change increases the z-index of lightbox so that it appears on top of application chrome (headers etc). The lightbox is a full screen image viewer and if things appear on top of it, and block the lightbox controls.
A recent change in a product using lunar caused the lightbox controls to be covered and unusable.
n/a (no visual change)
> fix:[Lightbox] Increase z-index

- packages/core/src/components/Modal/index.tsx
- packages/core/src/components/Modal/styles.ts
Allow for optional `zIndex` to be passed to Modal.
We want to override z-index for Modals that are in a Lighbox component where a recent change increased the z-index https://github.com/airbnb/lunar/pull/411. This allows to bring such Modals to the front.
Tested in storybook
> update(Modal): Add optional zIndex to props

- packages/apollo/README.md
- packages/apollo/package.json
- packages/apollo/src/components/Mutation/index.tsx
- packages/apollo/src/components/Mutation/story.tsx
- packages/apollo/src/components/Provider/index.tsx
- packages/apollo/src/components/Query/index.tsx
- packages/apollo/src/components/Query/story.tsx
- packages/apollo/src/hooks/useMutation.ts
- packages/apollo/src/hooks/useQuery.ts
- packages/apollo/src/hooks/useSubscription.ts
- packages/apollo/src/index.ts
- packages/apollo/src/updaters/addToList.ts
- packages/apollo/src/updaters/removeFromList.ts
- packages/apollo/src/utils/prepareQuery.ts
- packages/apollo/test/components/Mutation.test.tsx
- packages/apollo/test/components/Provider.test.tsx
- packages/apollo/test/components/Query.test.tsx
- packages/apollo/test/index.test.ts
- packages/apollo/test/updaters/__snapshots__/addToList.test.ts.snap
- packages/apollo/test/updaters/__snapshots__/removeFromList.test.ts.snap
- packages/apollo/test/updaters/addToList.test.ts
- packages/apollo/test/updaters/removeFromList.test.ts
- packages/apollo/test/utils.ts
- packages/apollo/test/utils/getQueryName.test.ts
- packages/apollo/test/utils/prepareQuery.test.ts
- yarn.lock
Update Apollo client to v3 and GraphQL v15
Apollo client [v3](https://www.apollographql.com/blog/announcing-the-release-of-apollo-client-3-0/) has been out for quite some time and we want to make sure Lunar is up to date. This release contains quite a few breaking changes so this PR is following the [migration guide](https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/) consolidating packages to `@apollo/client` and taking care of breaking changes.
This PR also updates GraphQL to [v15](https://github.com/graphql/graphql-js/releases/tag/v15.0.0) making sure we're up to date.
Also migrated to use `lodash/fp`.
Updated unit tests. Tested in Storybook.
N/A
- I have updated or added …
> release(Apollo): Update to Apollo v3 and GraphQL v15 

- packages/apollo/README.md
- packages/apollo/package.json
- packages/apollo/src/components/Mutation/index.tsx
- packages/apollo/src/components/Mutation/story.tsx
- packages/apollo/src/components/Provider/index.tsx
- packages/apollo/src/components/Query/index.tsx
- packages/apollo/src/components/Query/story.tsx
- packages/apollo/src/hooks/useMutation.ts
- packages/apollo/src/hooks/useQuery.ts
- packages/apollo/src/hooks/useSubscription.ts
- packages/apollo/src/index.ts
- packages/apollo/src/updaters/addToList.ts
- packages/apollo/src/updaters/removeFromList.ts
- packages/apollo/src/utils/prepareQuery.ts
- packages/apollo/test/components/Mutation.test.tsx
- packages/apollo/test/components/Provider.test.tsx
- packages/apollo/test/components/Query.test.tsx
- packages/apollo/test/index.test.ts
- packages/apollo/test/updaters/__snapshots__/addToList.test.ts.snap
- packages/apollo/test/updaters/__snapshots__/removeFromList.test.ts.snap
- packages/apollo/test/updaters/addToList.test.ts
- packages/apollo/test/updaters/removeFromList.test.ts
- packages/apollo/test/utils.ts
- packages/apollo/test/utils/getQueryName.test.ts
- packages/apollo/test/utils/prepareQuery.test.ts
- yarn.lock
Reverts airbnb/lunar#413
This should've been a major release not a patch release. I was under the impression that PR title would pick up the `release` keyword. Reverting to publish another patch update. cc @alecklandgraf
> revert(Apollo): Update to Apollo v3 and GraphQL v15

- packages/apollo/README.md
- packages/apollo/package.json
- packages/apollo/src/components/Mutation/index.tsx
- packages/apollo/src/components/Mutation/story.tsx
- packages/apollo/src/components/Provider/index.tsx
- packages/apollo/src/components/Query/index.tsx
- packages/apollo/src/components/Query/story.tsx
- packages/apollo/src/hooks/useMutation.ts
- packages/apollo/src/hooks/useQuery.ts
- packages/apollo/src/hooks/useSubscription.ts
- packages/apollo/src/index.ts
- packages/apollo/src/updaters/addToList.ts
- packages/apollo/src/updaters/removeFromList.ts
- packages/apollo/src/utils/prepareQuery.ts
- packages/apollo/test/components/Mutation.test.tsx
- packages/apollo/test/components/Provider.test.tsx
- packages/apollo/test/components/Query.test.tsx
- packages/apollo/test/index.test.ts
- packages/apollo/test/updaters/__snapshots__/addToList.test.ts.snap
- packages/apollo/test/updaters/__snapshots__/removeFromList.test.ts.snap
- packages/apollo/test/updaters/addToList.test.ts
- packages/apollo/test/updaters/removeFromList.test.ts
- packages/apollo/test/utils.ts
- packages/apollo/test/utils/getQueryName.test.ts
- packages/apollo/test/utils/prepareQuery.test.ts
- yarn.lock
to: @alecklandgraf
Update Apollo client to v3 and GraphQL v15. Followup from https://github.com/airbnb/lunar/pull/413
Apollo client [v3](https://www.apollographql.com/blog/announcing-the-release-of-apollo-client-3-0/) has been out for quite some time and we want to make sure Lunar is up to date. This release contains quite a few breaking changes so this PR is following the [migration guide](https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/) consolidating packages to `@apollo/client` and taking care of breaking changes.
This PR also updates GraphQL to [v15](https://github.com/graphql/graphql-js/releases/tag/v15.0.0) making sure we're up to date.
Also migrated to use `lodash/fp`.
Updated unit tests. Tested in Storybook.
N/A
- My code follows the style guide of …
> breaking(Apollo): Update to Apollo v3 and Graphql v15
